### ISSUE TITLE
0.6.4: error with Jedi, auto-completion / intellisense not working: Python 2.7, Code 1.13.0, Ubuntu 16.04

### ISSUE THREAD

**Issue by tiangolo** [DonJayamanne/pythonVSCode#1010]
## Environment data
VS Code version:  1.13.0
Python Extension version:  0.6.4
Python Version:  `Python 2.7.13 :: Continuum Analytics, Inc.` (A conda environment).
OS and version: Ubuntu 16.04 (64  bits)

## Actual behavior

The "loading" window opens but the auto-completion never shows.

![screenshot from 2017-06-09 17-40-22](https://user-images.githubusercontent.com/1326112/26996861-fb163d36-4d3a-11e7-9466-0ed33946dba1.png)

I actually noticed it trying to "Go to definition". That didn't work either.

## Expected  behavior

Auto-completion should show up. And "Go to definition" should take to the definition.

## Steps to reproduce:  
-  Import a function from another file.
-  Try to run the auto-complete (`ctrl-space`)

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
N/A
```   
Your settings.json:   

First tried with normal settings:
```json
{
    "sync.gist": "58b38291276ec5c735dedfe8d9e73c7a",
    "sync.lastUpload": "2017-06-09T21:42:05.673Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "2017-04-28T18:58:16.246Z",
    "sync.version": 262,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "workbench.iconTheme": "vscode-great-icons",
    "terminal.integrated.shell.windows": "C:\\windows\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "todohighlight.isEnable": true,
    "sync.quietSync": false
}
```   

Then with modified settings based on suggestions I found on other issues here:

```json
{
    "sync.gist": "58b38291276ec5c735dedfe8d9e73c7a",
    "sync.lastUpload": "2017-06-09T21:42:05.673Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "2017-04-28T18:58:16.246Z",
    "sync.version": 262,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "workbench.iconTheme": "vscode-great-icons",
    "terminal.integrated.shell.windows": "C:\\windows\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
    "todohighlight.isEnable": true,
    "sync.quietSync": false,
    "python.devOptions": [
        "USERELEASEAUTOCOMP"
    ]
}
```

Note the:

```json
    "python.devOptions": [
        "USERELEASEAUTOCOMP"
    ]
```
Although the "Problems" output while editing the `settings.json` says that it's an `Unknown configuration setting`.

**Note**: There are "Windows specific" configurations as I sync my settings between Ubuntu and a Windows machine.

## Logs
Output from ```Python``` output panel  

```
N/A
```   
Output from ```Console window``` (Help->Developer Tools menu)

Error 1:

```
[Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:297
(anonymous) @ extensionHost.ts:152
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

Error 2:

```
[Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:297
(anonymous) @ extensionHost.ts:152
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

Error 3:

```
[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 582, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 559, in _process_request
    return self._write_response(self._serialize_tooltip(script.goto_definitions(), request['id']))
  File "release/jedi/api/__init__.py", line 366, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "release/jedi/api/__init__.py", line 298, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "release/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "release/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "release/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "release/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "release/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "release/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "release/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "release/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "release/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "release/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "release/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "release/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "release/jedi/evaluate/finder.py", line 176, in filter_name
    for names_dict, position in names_dicts:
  File "release/jedi/evaluate/finder.py", line 500, in global_names_dict_generator
    for names_dict in scope.names_dicts(True):
  File "release/jedi/evaluate/representation.py", line 719, in names_dicts
    for star_module in self.star_imports():
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/representation.py", line 738, in star_imports
    modules += module.star_imports()
  File "release/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "release/jedi/evaluate/representation.py", line 734, in star_imports
    name = i.star_import_name()
  File "release/jedi/parser/tree.py", line 994, in star_import_name
    return self.paths()[-1][-1]
IndexError: list index out of range


d.logExtensionHostMessage @ extensionHost.ts:297
(anonymous) @ extensionHost.ts:152
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Note**: Those 3 errors keep repeating and appearing on every new interaction that would normally trigger auto-completion.

**Comment by DonJayamanne** [comment]
Are you still experiencing this issue.

**Comment by tiangolo** [comment]
Nope. I think this was fixed in a recent release. But I also migrated the project to Python 3.6. So I'm not completely sure.

I will close this issue and re-open it if I see the issue again (or create a new one if the issue changes).

Thanks!
