### ISSUE TITLE
rename symbol not work now

### ISSUE THREAD

**Issue by abc100m** [DonJayamanne/pythonVSCode#104]
with the new version (0.3.5), "Rename Symbol"(F2) is not working now

here is the error output
```shell
stderr jediProxy
Error (stderr) Traceback (most recent call last):
  File "completion.py", line 313, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 300, in _process_request
    script.usages(), request['id']))
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\api\__init__.py", line 490, in usages
    names = usages.usages(self._evaluator, definitions, module)
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\api\usages.py", line 25, in usages
    for m in imports.get_modules_containing_name(evaluator, mods, search_name):
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\imports.py", line 505, in get_modules_containing_name
    c = check_python_file(p)
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\imports.py", line 473, in check_python_file
    return check_fs(path)
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\imports.py", line 482, in check_fs
    module = _load_module(evaluator, path, source)
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\imports.py", line 450, in _load_module
    module = load(source) if cached is None else cached.module
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\imports.py", line 436, in load
    dotted_path = path and compiled.dotted_from_fs_path(path, sys_path)
  File "d:\.vscode\extensions\donjayamanne.python-0.3.5\pythonFiles\jedi\evaluate\compiled\__init__.py", line 339, in dotted_from_fs_path
    if (fs_path.startswith(s) and len(path) < len(s)):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 133: ordinal not in range(128)
```

**Comment by DonJayamanne** [comment]
Please could you confirm you do not have any Unicode characters in your fille paths. Please try without any Unicode characters in your file paths.

**Comment by abc100m** [comment]
There is no Unicode characters in my file path, and it's strange that F2 works today.
