### ISSUE TITLE
Debugger hangs

### ISSUE THREAD

**Issue by AdamBJ** [DonJayamanne/pythonVSCode#1041]
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.5
Python Version:  3.5.2 
OS and version:  Ubuntu 16.04 LTS (running as a virtual machine in VMWare Player)

## Actual behavior
PyTest periodically hangs instead of running/debugging unit tests. In the case of debugging, rather than the status bar at the bottom of the screen turning orange, it remains blue and the "Running Tests" indicator seems to blink forever. Clicking it and selecting the "Stop running tests" command has no effect.

In order to proceed I have to close VS Code and open it again.

Here's a picture of the indicator bar when the bug happens:
![image](https://user-images.githubusercontent.com/8980400/27346568-7f512ab0-55a2-11e7-868a-200ce42d7cf3.png)

## Expected  behavior
The tests should run/debug as expected, or at least let me cancel them if they hang.

## Steps to reproduce:  
Hard to say as the problem is intermittent. I notice it most often when I try to debug a specific unit test by pressing the "Debug Test" button above the test definition.  Looking at the console log, the issue maybe be caused by a bug in "Jedi" (not sure what that is).

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        },
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "integratedTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "externalTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Pyramid",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "args": [
                "${workspaceRoot}/development.ini"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "Pyramid"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
```{
    "python.unitTest.pyTestArgs": [
        "Tests"
    ],
    "python.unitTest.pyTestEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
None

Output from ```Console window``` (Help->Developer Tools menu)
```extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
```

**Comment by DonJayamanne** [comment]
Please could you provide a repo or sample code for me to be able to replicate this issue.

**Comment by AdamBJ** [comment]
You can try with this repo: https://github.com/AdamBJ/Python-Prototyping

Try running any of the tests in the `Python-Prototyping/Tests` directory. Like I said, it's tough to know exactly what steps are required to replicate the issue, though. It happens fairly often, but I'm not sure what triggers it. Let me know if there's anything else I can do on my end.

**Comment by DonJayamanne** [comment]
Please could you send me the contents of your `settings.json` file located in your project directory (this isn't in the repo). 

Also, when you get this error, what's the output of the `Python Test Log` output channel?  
When ever tests run, everything is logged in this output window (channel). That would contain the details of the errors.

**Comment by AdamBJ** [comment]
User `settings.json`:
```
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.giosave*": true,
        "**/.vscode": true,
        "**/.cache": true,
        "**/__pycache__": true
    },
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "git.autofetch": false,
    "editor.find.autoFindInSelection": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "window.zoomLevel": 0
}
```

Workspace `settings.json`:
```
{
    "python.pythonPath": "/usr/bin/python3.5",
    "python.unitTest.pyTestArgs": [
        "Tests"
    ],
    "python.unitTest.pyTestEnabled": true,
    "editor.find.autoFindInSelection": true
}
```

As far as I remember, nothing is output to the `Python Test Log`, it seems to hang before anything is outputted. I'll double check that, though.

**Comment by AdamBJ** [comment]
@DonJayamanne I found a way to reliably reproduce the problem. These are the steps I followed:

1. In `test_bad_input4` in `test_csv_json_transducer.py`, add `test = 2` after `pack_size=64` (line 51). *Don't save the file*.
2. Try to debug the test by pressing the `Debug Test` button right above the `test_bad_input4` definition. You should get `Error: undefined` in the `Python Test Log`. Immediately press the `Debug Test` button again to retry the debug operation. The tests will hang in the manner I described (the status bar doesn't turn orange, it stays blue and the tests run forever).

When I opened up the developer console to try and get more information about the undefined error I found this:

```
There was an error in running the tests.
e.doShow @ messageService.ts:125
```

**Comment by DonJayamanne** [comment]
@AdamBJ Apologies for never getting back to you. I believe I have found the issue. running the debugger in VS Code causes VS Code to automatically save changes to the file. When changes are made to a file the unit test framework then starts to re-discover tests (at this moment, it ensures any previous unit test operations are cancelled - and the debugging is is one such previous operation which gets).
