### ISSUE TITLE
Developer Console Error: 'no such file or directory, mkdir' when no .vscode directory exists

### ISSUE THREAD

**Issue by mattbierner** [DonJayamanne/pythonVSCode#1064]
## Environment data
VS Code version:   1.14.0-insider
Python Extension version:  0.6.7
Python Version:  any
OS and version:    MacOS 10.12.5

## Steps to reproduce:  
-  Open a workspace without any `.vscode` directory
-  Open a python file

## Bug
The following is logged in the vscode developer console:

```
ENOENT: no such file or directory, mkdir '"/PROJECT/.vscode': Error: ENOENT: no such file or directory, mkdir '"/PROJECT/.vscode'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Generator.generateTags (/Users/mattbierner/.vscode-insiders/extensions/donjayamanne.python-0.6.7/out/client/workspaceSymbols/generator.js:40:16)
    at Generator.generateWorkspaceTags (/Users/mattbierner/.vscode-insiders/extensions/donjayamanne.python-0.6.7/out/client/workspaceSymbols/generator.js:26:21)
    at utils_1.fsExistsAsync.then.exits (/Users/mattbierner/.vscode-insiders/extensions/donjayamanne.python-0.6.7/out/client/workspaceSymbols/main.js:65:42)
e.onUnexpectedError @ shell.ts:443
```

**Comment by DonJayamanne** [comment]
What is your workspace path?  
What is this '/PROJECT/' path that is logged in the error message?

**Comment by mattbierner** [comment]
PROJECT is the path to the workspace. I just replaced it in the log
