### ISSUE TITLE
can not run debugging on linux

### ISSUE THREAD

**Issue by faqin** [DonJayamanne/pythonVSCode#111]
In linux mint, debugging will prompt debugger terminates unexpectedly，
how to solve this problem？

**Comment by leesoh** [comment]
I have the same problem. I've configured everything as per the Debugging (https://github.com/DonJayamanne/pythonVSCode/wiki/Debugging) section, but still get "Debug adapter process has terminated unexpectedly".

**Comment by kdeltared** [comment]
Me too, the same problem with Ubuntu 14.04. I just keep pressing F5 until the debugger starts.

**Comment by faqin** [comment]
Forgive my English is very poor!
,I do not know vscode's problem or pythonVSCode‘s  problem
I upgraded to the latest version vscode,  see this error message:Canceled

**Comment by kdeltared** [comment]
The error in debug console:

```
Traceback (most recent call last):
  File "/tmp/tmp-18770TYtuoeTUVSuY/visualstudio_py_debugger.py", line 1646, in loop
    cmd()
  File "/tmp/tmp-18770TYtuoeTUVSuY/visualstudio_py_debugger.py", line 1918, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/tmp/tmp-18770TYtuoeTUVSuY/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/tmp/tmp-18770TYtuoeTUVSuY/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/tmp/tmp-18770TYtuoeTUVSuY/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
error: release unlocked lock
```

**Comment by wbartussek** [comment]
Same here. I'm on Ubuntu16.04, using Python 3.5 (/usr/bin/python3.5) with this path as "pythonPath": "/usr/bin/python3.5". My configuration in launch.json is:
```
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "pythonPath": "/usr/bin/python3.5",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },

```First error reported is: Debug adapter process has terminated unexpectedly
Second error: Cancelled (open launch.json)

**Comment by DonJayamanne** [comment]
Will look into this. i will need to set up such an env.

**Comment by leesoh** [comment]
I have a couple going if you need some logs etc. Also, thanks for all the
work on this extension!

**Comment by leesoh** [comment]
I'm also having this problem on Windows. It's less consistent, but still happens.

**Comment by faqin** [comment]
oh,
Still the same problem，NOT WORK
 Debug adapter process has terminated unexpectedly
Second error: Cancelled (open launch.json)

**Comment by DonJayamanne** [comment]
Hi, sorry for the delay. Please could you fire up the developer tools and check what errors are displayed in the webkit console Window.

**Comment by leesoh** [comment]
Sure thing!
```
Debug adapter process has terminated unexpectedly
Canceled: Error: Canceled
    at Object.w [as create] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:28776)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:103:26411
    at Object.p [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:23074)
    at Object.__dirname.undefined.F.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:26402)
    at __dirname.undefined.t.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:27723)
    at __dirname.undefined.t.Class.define._error (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:27240)
    at n (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:24945)
    at Object.p [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:23074)
    at Object.__dirname.undefined.F.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:26402)
    at __dirname.undefined.t.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:27723)
WARNING: Promise with no error callback:undefined
Error: Promise did not implement oncancel(â€¦)
```

**Comment by DonJayamanne** [comment]
Thanks

**Comment by faqin** [comment]
hi .
a good news, it can run on debian,
try it on debian!!!

I was finally able to use it on linux!!!!
@DonJayamanne @cbenz @leesoh @kdeltared @wbartussek

**Comment by DonJayamanne** [comment]
Hi @leesoh , @kdeltared , @faqin , @wbartussek , are you guys still having this same issue?
If not please let me know, I'd like to get this resolved, thanks.

**Comment by faqin** [comment]
oh, yes, I have not encountered this problem, thanks for your work!

**Comment by faqin** [comment]
oh, yes, I have not encountered this problem,  thanks for your work! @DonJayamanne

**Comment by DonJayamanne** [comment]
Excellent, if that's the case I'll be closing this issue.

**Comment by leesoh** [comment]
Hi Don,

I still have the debugging issue on Windows, on Linux (fresh-ish install) I now get continually re-prompted to create my launch.json and can't run. I'll see if I can get it figured out this week and will get back to you. The problem was occurring as recently as one or two weeks ago.

**Comment by leesoh** [comment]
Looks like it was related to a bug (https://github.com/Microsoft/vscode/issues/7291). Fixed and now I'm able to confirm that the same problem is happening.

**Comment by DonJayamanne** [comment]
@leesoh, as this is related to #40, i'll leave this thread and move to #40.
