### ISSUE TITLE
command 'python.python-debug.startSession' not found using 64-bit VS code

### ISSUE THREAD

**Issue by banpower1** [DonJayamanne/pythonVSCode#1167]
## Environment data
VS Code version:  1.15.0
Python Extension version: 0.7.0
Python Version: 3.6.1
OS and version: Windows 10 64-bit 1607

## Actual behavior
hitting debug gives a pop-up error from VS code reading "command 'python.python-debug.startSession' not found"

## Expected  behavior
no error and running the script

## Steps to reproduce:  
using a .py file and hitting Start Debugging

## Logs
Output from ```Console window``` (Help->Developer Tools menu)
```
command 'python.python-debug.startSession' not found: Error: command 'python.python-debug.startSession' not found
    at t._tryExecuteCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1080951)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1080790
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59188)
    at t.executeCommand (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:1080764)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:306515
    at n.Class.define.cancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59188)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:306412
    at n.Class.derive._oncancel.then (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:59188)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:305685
    at Object.g [as _notify] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:28:52362)
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ actionRegistry.ts:156
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_chainedError @ winjs.base.raw.js:1031
n @ winjs.base.raw.js:736
then @ winjs.base.raw.js:1436
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
l @ winjs.base.raw.js:1813
r.forEach.$.then.o.(anonymous function) @ winjs.base.raw.js:1838
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
then @ winjs.base.raw.js:1566
enter @ winjs.base.raw.js:747
_run @ winjs.base.raw.js:1068
_setCompleteValue @ winjs.base.raw.js:1052
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
l @ winjs.base.raw.js:1813
r.forEach.$.then.o.(anonymous function) @ winjs.base.raw.js:1838
g @ winjs.base.raw.js:1170
enter @ winjs.base.raw.js:852
_run @ winjs.base.raw.js:1068
_completed @ winjs.base.raw.js:1036
(anonymous) @ async.ts:643
(anonymous) @ C:\Program Files\Microsoft VS Code\resources\app\node_modules\graceful-fs\graceful-fs.js:78
readFileAfterClose @ original-fs.js:416
```

**Comment by TiemenSch** [comment]
Have you actually setup any launch configurations? (.vscode/launch.json)

If you don't have that:
You can setup the default ones by going to the Debug tab and clicking on the "clog" settings wheel.

**Comment by banpower1** [comment]
I have a bunch of different launch.json options that came with the plugin, using the default one with the modification of having it run on launch.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python - Run",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }, 
       (removed 11 more configurations)
    ]
}
```

**Comment by DonJayamanne** [comment]
@banpower1 Please could you confirm this problem still persists?

**Comment by banpower1** [comment]
@DonJayamanne confirmed right now to still exist, using version 0.7.0 of the plugin, 3.6.1 python and Visual Studio Code version 1.15.1 64-bit

**Comment by DonJayamanne** [comment]
Please could you uninstall the extension and try this once again.

**Comment by banpower1** [comment]
Reinstalling the plugin seems to have fixed it, not certain why i didn't think of this straight away

**Comment by DonJayamanne** [comment]
Fixed in the latest version
