### ISSUE TITLE
[FR] auto completion for unsaved file.

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#1194]
RT.

**Comment by DonJayamanne** [comment]
Please provide more info, this works today.

**Comment by bluehezihhh** [comment]
HI, this is the log

`Running the contributed command:'python.autoImportAtCursor' failed.: Error: Running the contributed command:'python.autoImportAtCursor' failed.
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328997)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
(anonymous) @ errors.ts:49
(anonymous) @ errors.ts:44
`

`ARNING: Promise with no error callback:221`

'Objecterror: Error: Running the contributed command:'python.autoImportAtCursor' failed.
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328997)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)message: "Running the contributed command:'python.autoImportAtCursor' failed."name: "Error"stack: "Error: Running the contributed command:'python.autoImportAtCursor' failed.↵    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328997)↵    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)↵    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)↵    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)↵    at _combinedTickCallback (internal/process/next_tick.js:67:7)↵    at process._tickCallback (internal/process/next_tick.js:98:9)"__proto__: Objectconstructor: Error()arguments: nullcaller: nullcaptureStackTrace: captureStackTrace()arguments: nullcaller: nulllength: 2name: "captureStackTrace"__proto__: ()apply: apply()arguments: nullcaller: nulllength: 2name: "apply"__proto__: ()apply: apply()arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>length: 1name: "Error"prototype: ObjectstackTraceLimit: 10__proto__: ()message: ""name: "Error"toString: toString()arguments: nullcaller: nulllength: 0name: "toString"__proto__: ()apply: apply()arguments: nullcaller: nulllength: 2name: "apply"__proto__: ()arguments: (...)bind: bind()arguments: nullcaller: nulllength: 1name: "bind"__proto__: ()call: call()caller: (...)constructor: Function()arguments: nullcaller: nulllength: 1name: "Function"prototype: ()apply: apply()arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>__proto__: ()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()arguments: nullcaller: nulllength: 1name: "[Symbol.hasInstance]"__proto__: ()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()exception: nullhandler: undefinedid: 221parent: undefinedpromise: n.Class.derive._oncancel_errorId: 221_isException: false_listeners: null_nextState: null_oncancel: null_state: Object_value: Error: Running the contributed command:'python.autoImportAtCursor' failed.
    at t.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:328997)
    at t.e.handle (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:308751)
    at s (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:188848)
    at h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)done: (e,t)then: (e,t)arguments: (...)caller: (...)length: 2name: "then"prototype: Object__proto__: ()[[FunctionLocation]]: winjs.base.raw.js:1396[[Scopes]]: Scopes[6]__proto__: e_cancelAction: ()_cleanupAction: ()_oncancel: nullconstructor: (e,t)__proto__: Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()arguments: nullcaller: nulllength: 1name: "set __proto__"__proto__: ()apply: apply()arguments: nullcaller: nulllength: 2name: "apply"__proto__: ()apply: apply()arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()arguments: nullcaller: nulllength: 1name: "set __proto__"__proto__: ()apply: apply()arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()[[FunctionLocation]]: <unknown>[[FunctionLocation]]: <unknown>arguments: (...)bind: bind()call: call()caller: (...)constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()get arguments: ThrowTypeError()set arguments: ThrowTypeError()get caller: ThrowTypeError()set caller: ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>
temp1
temp2
"Error"
undefined'

what's the problem about it? Thank you a lot!

**Comment by Cologler** [comment]
@DonJayamanne 

For example, if create a untitled doc in vscode:

![picpick-20170905-220749-001](https://user-images.githubusercontent.com/10906962/30065207-b22c4476-9286-11e7-9cb5-7b3e583f4720.png)

Seems no auto completion here.
