### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by qmmp123** [DonJayamanne/pythonVSCode#1232]
## Environment data
VS Code version:  Версия 1.16.1
Python Extension version:  0.7.0
Python Version:   3.6.2
OS and version:    ubuntu-16.04

## Actual behavior
a = list()
a. #completions of class list 
## Expected  behavior
a = list()
a. #completions of words which used in file
## Steps to reproduce:  
-  Just type my code
-  

## Logs
Output from ```Python``` output panel  
```
did not find it sorry
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:305:12)
	at sendCommand (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/jediProxy.js:419:20)
	at JediProxy.sendCommand (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/jediProxy.js:128:16)
	at JediProxyHandler.sendCommand (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/jediProxy.js:545:31)
	at PythonHoverProvider.<anonymous> (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/hoverProvider.js:103:54)
	at Generator.next (<anonymous>)
	at /home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/hoverProvider.js:7:71
	at Promise (<anonymous>)
	at __awaiter (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/hoverProvider.js:3:12)
	at PythonHoverProvider.provideHover (/home/qmmp123/.vscode/extensions/donjayamanne.python-0.7.0/out/client/providers/hoverProvider.js:81:16)
```

**Comment by DonJayamanne** [comment]
1. Is python in the current path? (type ```python ---version``` in your terminal window)  
2. Are you using a virtual environment?  

3. Instructions to get content from output panel:
- Please could you double check the output panel (this is the output window on the bottom).
- There are a couple of tabs, ```Problems | Output | Debug Console | Terminal```
- I'd like you to click ```Output``` and form the dropdown select ```Python```
- There must be something in the output window

4. Please confirm that the only errror displayed in the ```Console window``` is what you have provided above.

Thanks

**Comment by qmmp123** [comment]
So I have solved my problem. I deleted path for jedi in my settings. But I don't get autocompletions after 
```
self. # there are no methods from object class 
```

**Comment by qmmp123** [comment]
do you use jedi for autocomplete?

**Comment by DonJayamanne** [comment]
Yes

**Comment by DonJayamanne** [comment]
@qmmp123 please could you provide a code sample and provide steps to replicate the issue.
Thanks
