### ISSUE TITLE
python debugger crashes with KeyError

### ISSUE THREAD

**Issue by hwalia282** [DonJayamanne/pythonVSCode#1391]
## Environment data
VS Code version:  1.19.1
Python Extension version:  0.9.1
Python Version:   3.4.3
OS and version:    Ubuntu 14.04 LTS

## Actual behavior
Press F5 to launch debugger but it does not stop at any of the breakpoints.  Step Over, Step Into and Step Out are greyed out. 

## Expected  behavior

Stop at breakpoint

## Steps to reproduce:  
Here is the python code I used:

```
import platform
version = platform.python_version()
print(version)
print("Your python version is Python %s" % version)
```

I inserted a breakpoint at line 2.

Here is launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "console": "integratedTerminal",
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {
                "PORT": "8080"
            }
        }
    ]
}
```

## Logs
Output from ```Python``` output panel  
no output

Output from ```Console window``` (Help->Developer Tools menu)
no output

From terminal I see this:
```
hwalia@ubuntu:~/DevNet/code/devnet-express-cloud-collab-code-samples/itp/collab-tools-visual-studio-code-ide-itp$ cd /home/hwalia/DevNet/code/devnet-express-cloud-collab-code-samples/itp/collab-tools-visual-studio-code-ide-itp ; env "PORT=8080" "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /usr/bin/python3 /home/hwalia/.vscode/extensions/ms-python.python-0.9.1/pythonFiles/PythonTools/visualstudio_py_launcher.py /home/hwalia/DevNet/code/devnet-express-cloud-collab-code-samples/itp/collab-tools-visual-studio-code-ide-itp 40348 34806ad9-833a-4524-8cd6-18ca4aa74f14 DUMMYVALUE /home/hwalia/DevNet/code/devnet-express-cloud-collab-code-samples/itp/collab-tools-visual-studio-code-ide-itp/version.py
Traceback (most recent call last):
  File "/home/hwalia/.vscode/extensions/ms-python.python-0.9.1/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1729, in loop
    cmd()
  File "/home/hwalia/.vscode/extensions/ms-python.python-0.9.1/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1914, in command_resume_thread
    thread = THREADS[tid]
KeyError: -1219491840
```

**Comment by hwalia282** [comment]
Uninstalled.
