### ISSUE TITLE
All python commands not found, can't run any python functionallity nor unistall python extension

### ISSUE THREAD

**Issue by pjanowski** [DonJayamanne/pythonVSCode#1394]
## Environment data
VS Code version:  Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Python Extension version:  0.9.1
Python Version:   3.6.3 Anaconda
OS and version:    OS Name	Microsoft Windows 10 Enterprise  Version	10.0.14393 Build 14393

## Actual behavior
Same issues as reported 
1. https://github.com/DonJayamanne/pythonVSCode/issues/892
2. https://github.com/DonJayamanne/pythonVSCode/issues/1325
3. here https://github.com/Microsoft/vscode-python/issues/24.

All three issues have been closed and the consensus seems to be to uninstall and reinstall but doing this does not resolve the issue for me. 

Launching VS Code shows "Cannot find module 'reflect-metadata'." error.

4. Also, I am unable to uninstall the python extension: just goes into "uninstalling" and never finishes.

## Expected  behavior
1. F5 should run the script and stop at break point.
2. All python commands should be accessible.
3. Python:Select Interpreter should open a drop down
4. Uninstalling Python extension should uninstall the python extension

## Steps to reproduce: 
1. Hit F5
2. Ctrl+Shift+P  and select any Python command
3. Ctrl+Shift+P and select "Python:Select Interprer"
4. Go to extensions tab, click on Python extension and click on "uninstall"

## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2571 [Extension Host] debugger listening on port 9333
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2569 [Extension Host] debugger inspector at %cDebugger listening on port 9333.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9333/94e7ec7b-1e06-4718-8d9f-5fd665f35112

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Activating extension `ms-python.python` failed: Cannot find module 'reflect-metadata'.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Activating extension `ms-python.python` failed:  Cannot find module 'reflect-metadata'
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:249
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] Here is the error stack:  Error: Cannot find module 'reflect-metadata'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\paulano\.vscode\extensions\ms-python.python-0.9.1\out\client\extension.js:14:5)
	at Object.<anonymous> (C:\Users\paulano\.vscode\extensions\ms-python.python-0.9.1\out\client\extension.js:197:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4054 Activating extension `ms-python.python` failed: Cannot find module 'reflect-metadata'.
t._logMessageInConsole @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4054
4dom.ts:183 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:136 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
actionbar.ts:82 [Violation] 'setTimeout' handler took 88ms
dom.ts:183 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:136 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
dom.ts:183 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
browser.ts:136 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
dom.ts:183 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
messageService.ts:126 command 'python.setInterpreter' not found
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1024
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:535
messageService.ts:126 command 'python.goToPythonObject' not found
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
e.resume @ messageService.ts:64
(anonymous) @ workbench.ts:1024
e.fire @ event.ts:142
(anonymous) @ quickOpenController.ts:535
2messageService.ts:126 Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
_.onServerExit @ rawDebugSession.ts:535
(anonymous) @ rawDebugSession.ts:449
emitTwo @ events.js:111
emit @ events.js:194
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
```

**Comment by DonJayamanne** [comment]
Please create an issue on the Microsoft repo. I'll look into the issue there. https://github.com/Microsoft/vscode-python/issues

Looks like you have a corrupted installation on the extension. 
If you are unable to install the extension, please report an issue on the vscode repo, as it's out of our hands. Once you have it installed properly and still face issue, then please do feel free to file an issue.

**Comment by pjanowski** [comment]
Solved:
1) manually delete the python extension (~/.vscode/extensions/ )
2) reinstall vscode
3) update vscode
4) reinstall the python extension

**Comment by philosophicles** [comment]
For benefit of other readers having this problem: I did not need to reinstall VS Code to fix this. Following @pjanowski 's steps (1) and (4) alone fixed this for me. 

Thanks @pjanowski!

**Comment by vtortola** [comment]
Yes, manually deleting the extension and adding it again worked for me as well 👍
