### ISSUE TITLE
Python debugger not running when the start button is clicked on.

### ISSUE THREAD

**Issue by SuryavaBhattacharya** [DonJayamanne/pythonVSCode#1408]
## Environment data

- VS Code version: 1.21.1
- Extension version (available under the Extensions sidebar): 2018.3.1
- OS and version: Windows 10, version 1709
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda 5.1.0 Python 3.6.4
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
- Relevant/affected Python packages and their versions: XXX

## Actual behavior

I start the Debug, but it keeps loading and does not actually start the debug process: 
![image](https://user-images.githubusercontent.com/36743750/38293138-504edb30-37de-11e8-801e-dbd8522782e7.png)
The blue bar keeps moving left to right but the debug process doesn't start.
I have checked whether it's an issue with the Debugger by Debugging a .c file, but that works just fine, so it must be a problem with Python.
In the integrated terminal, within cd command, this comes up:
" ${env:PYTHONIOENCODING}='UTF-8'; ${env:PYTHONUNBUFFERED}='1'; & 'C:\Users\surya\Anaconda3\python.exe'".... "'51334' '34806ad9-833a-4524-8cd6-18ca4aa74f14' 'RedirectOutput,RedirectOutput'"

## Expected  behavior

The Debug starts and then runs

## Steps to reproduce:
1. Unsure; it was working before, but isn't anymore...

## Logs
Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

```
##########Linting Output - pylint##########
No config file found, using default configuration

--------------------------------------------------------------------

Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```   

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
[C:\Users\surya\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
extensionService.ts:786 [C:\Users\surya\.vscode\extensions\ms-vscode.cpptools-0.16.1]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
TMSyntax.ts:43 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: c:\Program Files\Microsoft VS Code\resources\app\extensions\python\syntaxes\MagicPython.tmLanguage.json.
New grammar file: C:\Users\surya\.vscode\extensions\magicstack.magicpython-1.0.12\grammars\MagicPython.tmLanguage
e.register @ TMSyntax.ts:43
TMSyntax.ts:43 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: C:\Users\surya\.vscode\extensions\James-Yu.latex-workshop-5.0.3\syntax\Bibtex.plist.
New grammar file: C:\Users\surya\.vscode\extensions\torn4dom4n.latex-support-1.5.1\grammars\BibTeX.json
e.register @ TMSyntax.ts:43
TMSyntax.ts:43 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: C:\Users\surya\.vscode\extensions\James-Yu.latex-workshop-5.0.3\syntax\LaTeX.plist.
New grammar file: C:\Users\surya\.vscode\extensions\torn4dom4n.latex-support-1.5.1\grammars\LaTeX.json
e.register @ TMSyntax.ts:43
TMSyntax.ts:43 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: C:\Users\surya\.vscode\extensions\James-Yu.latex-workshop-5.0.3\syntax\TeX.plist.
New grammar file: C:\Users\surya\.vscode\extensions\torn4dom4n.latex-support-1.5.1\grammars\TeX.json
e.register @ TMSyntax.ts:43
console.ts:136 [Extension Host] Congratulations, your extension "terminal" is now active!
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] Starting express server on port: 51692
console.ts:136 [Extension Host] using C:/Users/surya/.vscode/extensions/vsciot-vscode.vscode-arduino-0.2.11/vendor/node-usb-native/lib/native/usb-native_win32_1.7.3_x64.node
console.ts:136 [Extension Host] Python Extension: Failed to get conda environment list from conda Error: spawn conda ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
t.log @ console.ts:136

```

**Comment by DonJayamanne** [comment]
@SuryavaBhattacharya
You have filled this issue in the places. One would suffice.
