### ISSUE TITLE
Debugger stopped working

### ISSUE THREAD

**Issue by pck76** [DonJayamanne/pythonVSCode#182]
Hi,

The debugger has stopped working. 

Take a simple program like this:
```
print('this is just a test')
for i in range (1,500):
    print(i)
```

if I start the debugger, the first line is printed as expected, but then when I press F11 to move to the next instruction, I get this error:

```
Traceback (most recent call last):
  File "/private/var/folders/3l/_qhlyr0j0p576341582rw0zc0000gn/T/tmp-18001uwXdAII01Dtk/visualstudio_py_debugger.py", line 1646, in loop
    cmd()
  File "/private/var/folders/3l/_qhlyr0j0p576341582rw0zc0000gn/T/tmp-18001uwXdAII01Dtk/visualstudio_py_debugger.py", line 1918, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/private/var/folders/3l/_qhlyr0j0p576341582rw0zc0000gn/T/tmp-18001uwXdAII01Dtk/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/private/var/folders/3l/_qhlyr0j0p576341582rw0zc0000gn/T/tmp-18001uwXdAII01Dtk/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/private/var/folders/3l/_qhlyr0j0p576341582rw0zc0000gn/T/tmp-18001uwXdAII01Dtk/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
RuntimeError: release unlocked lock

```

earlier this morning VScode told me I had to update your extension. I did so, and I think after that I started getting this error.

**Comment by DonJayamanne** [comment]
Please try the following:
- Clear any variables in the watch window before staying to debug.
- Try debugging someile with just one print statement

**Comment by pck76** [comment]
Hi Don,

Thanks for the reply. 
Removing the variables from watch seems to have worked, in the sense the debugger doesn't break.

However, even during execution it looks like everything is slower than it should be. 

I've tested a bigger script in the Terminal and also in VSCode. The script contains a loop where each iteration calls a function etc.
- in VScode the first 3 iterations take 1 seconds each, then this grows to around 7 seconds each.
- In terminal, every iteration is below 1 second, from beginning to end.

**Comment by DonJayamanne** [comment]
@pck76 , what variable did you have in the watch window? I'd like to bette handle these situations.

I've tested the same code you have, and it works as expected. Basically the entire loop completes instantly, my guess is less than a second.

You might have some anti virus scanners that causing the delay or similar.
The way the debugger works is, a socket server is created and data is transferred across a random port.

**Comment by DonJayamanne** [comment]
@pck76 , are you still have to replicate this issue
