### ISSUE TITLE
Debugger fails to run

### ISSUE THREAD

**Issue by H-SG** [DonJayamanne/pythonVSCode#240]
This seems to be related but distinct to issues #182, #135. If I have watches defined and enter commands into the debug console during debugging (i.e. after a line of code has finished processing) the following error output appears:

```
Traceback (most recent call last):
  File "/home/zander/.vscode/extensions/donjayamanne.python-0.3.18/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1646, in loop
    cmd()
  File "/home/zander/.vscode/extensions/donjayamanne.python-0.3.18/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1918, in command_execute_code
    thread.run_on_thread(text, cur_frame, eid, frame_kind, repr_kind)
  File "/home/zander/.vscode/extensions/donjayamanne.python-0.3.18/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/home/zander/.vscode/extensions/donjayamanne.python-0.3.18/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/home/zander/.vscode/extensions/donjayamanne.python-0.3.18/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
error: release unlocked lock
```

The only way to get debugging working again is to remove the watches, run debugger once, and redefine them again before being able to use them again.

**Comment by DonJayamanne** [comment]
@H-SG, please could you provide the instructions to replicate this issue.
Please post the instructions on #135 
Thanks
