### ISSUE TITLE
Debugger error "RuntimeError: release unlocked lock"

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#298]
Reported on reddit: 
https://www.reddit.com/r/programming/comments/51t7no/visual_studio_code_august_2016_15/d7f31jv

> I occasionally get "RuntimeError: release unlocked lock" when debugging Python.

**Comment by baburajpb** [comment]
`
  File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1246, in run_on_thread
    self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
  File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1238, in schedule_work
    self.unblock()
  File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1234, in unblock
    self._block_lock.release()
RuntimeError: release unlocked lock`

**Comment by peringz** [comment]
This is what I see in the console.

`File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1246, in run_on_thread
  self.schedule_work(lambda : self.run_locally(text, cur_frame, execution_id, frame_kind, repr_kind))
File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1238, in schedule_work
  self.unblock()
File "/Users/<user>/.vscode/extensions/donjayamanne.python-0.3.22/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1234, in unblock
  self._block_lock.release()
RuntimeError: release unlocked lock
`

**Comment by DonJayamanne** [comment]
@peringz, thanks for the immediate feedback.

- Please could you ensure you have updated the python extension to the latest version 0.3.22 (released yesterday)  
- What is your OS? 
- Please could you provide a sample program (or instructions) for me to replicate this at my end? 
- What version of Python are you using? 

Thanks

**Comment by peringz** [comment]
@DonJayamanne I'm using extension version 0.3.22 on OS X and using Python 3.5.2 (tried 2.7.10 and got the same results)

A simple program like the one below will often throw this exception at a random interval. An error is thrown only when the first line of code or a breakpoint is hit.

```
def next_id(arr):
    nextid = 0
    while nextid in arr:
        nextid += 1
    return nextid

print(next_id([0, 1, 2, 3, 4, 12, 11, 8, 9]))
```

**Comment by DonJayamanne** [comment]
@peringz, one last question. Do you have any watch variables? Thanks

**Comment by peringz** [comment]
@DonJayamanne I had three, removed them and did some quick testing. Not able to reproduce the error any longer.

**Comment by DonJayamanne** [comment]
@peringz
Oh no, do you  remember what variables you had. Please could you add them back. And try again.

**Comment by peringz** [comment]
@DonJayamanne  I don't know the variable names. But I was able to replicate the problem by adding two invalid watch variables (foo and bar)
<img width="951" alt="vscode_python" src="https://cloud.githubusercontent.com/assets/338181/18407388/c7090a42-76d4-11e6-914d-0ea9c750e66f.png">

**Comment by DonJayamanne** [comment]
Great thanks, will check this out tonight.

**Comment by DonJayamanne** [comment]
@peringz , i'm unable o replicate this issue at my end. **Will keep trying**. 
However there's a ray of hope, I have fixed an issue that may be related to this (#292). Will release a build soon.

**Comment by DonJayamanne** [comment]
@peringz , will close this as the fix for #292 should have resolve this issue. If not , please re-open the issue.

**Comment by staffann** [comment]
I get the same problem with version 0.5.6:
Traceback (most recent call last):
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1725, in loop
    cmd()
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 2022, in command_enum_children
    thread.enum_child_on_thread(text, cur_frame, eid, frame_kind)
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1345, in enum_child_on_thread
    self.schedule_work(lambda : self.enum_child_locally(text, cur_frame, execution_id, frame_kind))
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1316, in schedule_work
    self.unblock()
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1312, in unblock
    self._block_lock.release()
RuntimeError: release unlocked lock

Using python 3. Have some different watch variables. The problem occurs when I step inside the code.

**Comment by ngawangtrinley** [comment]
I'm on Linux and I get the same problem when I "step into" the code in a fast sequence. If I wait half a second or a second between each time I hit F11 I don't have the problem. I didn't have the problem in Windows.

**Comment by guiambros** [comment]
Likewise; I can now reproduce in a very consistent manner. If I wait 0.2s before I press F10/F11, it works well. If I hold the F10 key pressed, it will execute for 3-4 iterations and then cause the error and lock up the session. I have to then stop debugger and start again.

Not a huge issue, but a bit annoying when you want to advance a long for-loop without stepping out or setting a breakpoint.

Version 0.5.8 (3 February 2017)

**Comment by mostafaeweda** [comment]
I keep hitting this issue - I'm willing to help fix it, but need guidance where to start.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#65
