### ISSUE TITLE
Error using 'select workspace interpreter'

### ISSUE THREAD

**Issue by cg-cnu** [DonJayamanne/pythonVSCode#357]
vscode version: 1.5.3
Extension Version: 0.3.24 

Following this [wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Miscellaneous#select-an-interpreter) page to setup python interpreter.
Gave the following error.
`` command 'python.setInterpreter' not found ``

**Comment by cg-cnu** [comment]
I did a little bit of debugging and found the issue. 
I have updated both vscode and python extention recently. 

Something might have went wrong and the extension itself is not actually activated. 
Opening the dev tools show these errors. 
```
Extension Host] Activating extension `donjayamanne.python` failed:  Cannot find module './isArrayLike'
threadService.ts:217 [Extension Host] Here is the error stack:  Error: Cannot find module './isArrayLike'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.I.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:25921)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/salapati/.vscode/extensions/donjayamanne.python-0.3.24/node_modules/lodash/_isIterateeCall.js:2:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
Just to test out I re installed the extension and everything is working fine. 

Thanks for the work mr. @DonJayamanne
