### ISSUE TITLE
Extract variable failed

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#468]
Version 0.5.0, Windows 10

Extracting the argument to print from `print('Hello {0}'.format(name))` failed:

![extract-variable-failed](https://cloud.githubusercontent.com/assets/9205389/19747878/3e74267e-9b93-11e6-9afc-dded5c3a2ac5.PNG)

The file:
```
"""Hello library"""

def read_name():
    """Return a name read from stdin."""
    return input('Name: ')

def printHello(name):
    """Say hello to name on stdout.
    :param name: The name.
    """
    print('Hello {0}'.format(name))
```

The output:
##########Refactor Output##########
Error in refactoring:
Refactor failed.   
Traceback (most recent call last):
  File "refactor.py", line 266, in watch
    self._process_request(self._input.readline())
  File "refactor.py", line 251, in _process_request
    request['start']), int(request['end']), request['name'])
  File "refactor.py", line 195, in _extractVariable
    refactor.refactor()
  File "refactor.py", line 89, in refactor
    self.onRefactor()
  File "refactor.py", line 133, in onRefactor
    self.project, self.resource, self._startOffset, self._endOffset)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 89, in __init__
    super(ExtractVariable, self).__init__(*args, **kwds)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 43, in __init__
    self.end_offset = self._fix_end(resource.read(), end_offset)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 51, in _fix_end
    while offset > 0 and source[offset - 1].isspace():
IndexError: string index out of range

Traceback (most recent call last):
  File "refactor.py", line 266, in watch
    self._process_request(self._input.readline())
  File "refactor.py", line 251, in _process_request
    request['start']), int(request['end']), request['name'])
  File "refactor.py", line 195, in _extractVariable
    refactor.refactor()
  File "refactor.py", line 89, in refactor
    self.onRefactor()
  File "refactor.py", line 133, in onRefactor
    self.project, self.resource, self._startOffset, self._endOffset)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 89, in __init__
    super(ExtractVariable, self).__init__(*args, **kwds)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 43, in __init__
    self.end_offset = self._fix_end(resource.read(), end_offset)
  File "C:\Users\chrmarti\.vscode-insiders\extensions\donjayamanne.python-0.5.0\pythonFiles\rope\refactor\extract.py", line 51, in _fix_end
    while offset > 0 and source[offset - 1].isspace():
IndexError: string index out of range

```

**Comment by chrmarti** [comment]
Simpler examples seem to fail with the same error.

**Comment by chrmarti** [comment]
Extracting a method fails with a similar error. I'm using Python 3.5.2.
