### ISSUE TITLE
getAbsolutePath: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by IgorNovozhilov** [DonJayamanne/pythonVSCode#471]
### Error Message

![2016-10-27_16h20_24](https://cloud.githubusercontent.com/assets/3082812/19769319/9bf32c0c-9c63-11e6-8d15-becbc4300485.png)

### Version:

![2016-10-27_16h27_43](https://cloud.githubusercontent.com/assets/3082812/19769092/b0bea04a-9c62-11e6-81e9-a711515c3828.png)

![2016-10-27_16h27_51](https://cloud.githubusercontent.com/assets/3082812/19769093/b2b37fe2-9c62-11e6-8df3-209da9e3d958.png)

### Reproduce

-1. Сreate a file user settings:
```js
{
   "editor.tabSize": 3,
   "editor.insertSpaces": true,
   "editor.detectIndentation": false,
   "git.confirmSync": false,
   "python.linting.pep8Enabled": true,
   "python.linting.pylintEnabled": false,
   "window.zoomLevel": 0
}
```

-2. **Re-opening the VSCode when to opened the edit file Python**

### Reason

User settings replace the base, which leads to duplication of a function call `initializeSettings`

### Analysis

In `configSettings.js` append output debug info
```js
var RUN_initializeSettings_CNT = 1;
...
        var fs = require('fs')
        
        fs.appendFile('d:/test.log', 'run is ' + RUN_initializeSettings_CNT + '\n');
        fs.appendFile('d:/test.log',(new Error()).stack)
        
        fs.appendFile('d:/test.log', 'vscode.workspace.getConfiguration(\'python\'):\n')
        fs.appendFile('d:/test.log', JSON.stringify(vscode.workspace.getConfiguration('python'),null,'\t') + '\n\n')
        fs.appendFile('d:/test.log', 'pythonSettings.get(\'pythonPath\'):\n')
        fs.appendFile('d:/test.log', JSON.stringify(pythonSettings.get('pythonPath'),null,'\t') + '\n\n')
        fs.appendFile('d:/test.log', 'systemVariables.resolveAny(pythonSettings.get(\'pythonPath\'):\n')
        fs.appendFile('d:/test.log', JSON.stringify(systemVariables.resolveAny(pythonSettings.get('pythonPath')),null,'\t') + '\n\n')
        
        RUN_initializeSettings_CNT ++;
```

![2016-10-27_16h40_38](https://cloud.githubusercontent.com/assets/3082812/19769519/667c9ad0-9c64-11e6-8ef9-01524295d58b.png)

**run is 1** - `PythonSettings.pythonSettings = new PythonSettings();`
```
at Object.<anonymous> (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:153:33)
```

**run is 2** - Event: `onDidChangeConfiguration`
```
at PythonSettings.vscode.workspace.onDidChangeConfiguration (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:18:18)
```

So the first step in the class constructor we receive not a complete set of settings, only user settings:
```js
{
	"linting": {
		"pep8Enabled": true,
		"pylintEnabled": false
	}
}
```

Full `test.log`
```
run is 1

Error
    at PythonSettings.initializeSettings (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:33:38)
    at PythonSettings (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:20:14)
    at Object.<anonymous> (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:153:33)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.M.d._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:28163)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\providers\jediProxy.js:5:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

vscode.workspace.getConfiguration('python'):
{
	"linting": {
		"pep8Enabled": true,
		"pylintEnabled": false
	}
}

pythonSettings.get('pythonPath'):
undefined

systemVariables.resolveAny(pythonSettings.get('pythonPath'):
undefined

run is 2

Error
    at PythonSettings.initializeSettings (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:33:38)
    at PythonSettings.vscode.workspace.onDidChangeConfiguration (C:\Users\user1\.vscode-insiders\extensions\donjayamanne.python-0.5.0\out\client\common\configSettings.js:18:18)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:7190)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:15512)
    at t.$acceptConfigurationChanged (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:27089)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10162)
    at s (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21165)
    at p (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21842)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

vscode.workspace.getConfiguration('python'):
{
	"pythonPath": "python",
	"linting": {
		"enabled": true,
		"prospectorEnabled": false,
		"pylintEnabled": false,
		"pep8Enabled": true,
		"flake8Enabled": false,
		"pydocstyleEnabled": false,
		"mypyEnabled": false,
		"lintOnTextChange": true,
		"lintOnSave": true,
		"maxNumberOfProblems": 100,
		"pylintCategorySeverity": {
			"convention": "Information",
			"refactor": "Hint",
			"warning": "Warning",
			"error": "Error",
			"fatal": "Error"
		},
		"prospectorPath": "prospector",
		"pylintPath": "pylint",
		"pep8Path": "pep8",
		"flake8Path": "flake8",
		"pydocStylePath": "pydocstyle",
		"mypyPath": "mypy",
		"prospectorArgs": [],
		"pylintArgs": [],
		"pep8Args": [],
		"flake8Args": [],
		"pydocStyleArgs": [],
		"mypyArgs": [],
		"outputWindow": "Python"
	},
	"formatting": {
		"provider": "autopep8",
		"autopep8Path": "autopep8",
		"yapfPath": "yapf",
		"autopep8Args": [],
		"yapfArgs": [],
		"outputWindow": "Python"
	},
	"autoComplete": {
		"extraPaths": []
	},
	"unitTest": {
		"nosetestsEnabled": false,
		"nosetestPath": "nosetests",
		"pyTestEnabled": false,
		"pyTestPath": "py.test",
		"nosetestArgs": [],
		"pyTestArgs": [],
		"unittestEnabled": false,
		"unittestArgs": [
			"-v"
		],
		"outputWindow": "Python Test Log"
	},
	"terminal": {
		"executeInFileDir": false,
		"launchArgs": []
	},
	"jupyter": {
		"appendResults": true,
		"defaultKernel": "",
		"startupCode": [
			"%matplotlib inline"
		]
	}
}

pythonSettings.get('pythonPath'):
"python"

systemVariables.resolveAny(pythonSettings.get('pythonPath'):
"python"

```

**Comment by DonJayamanne** [comment]
This is due to a bug in VS Code Insiders (https://github.com/Microsoft/vscode/issues/14500#event-837643135)
