### ISSUE TITLE
TypeError: Cannot read property 'Write' of null

### ISSUE THREAD

**Issue by jeswaran** [DonJayamanne/pythonVSCode#474]
While trying to break into to a remote process after connecting, I am getting 

> TypeError: Cannot read property 'Write' of null

From the Console:

```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:93 TypeError: Cannot read property 'Write' of null
    at PythonProcess.Break (/Users/Jagan/.vscode/extensions/donjayamanne.python-0.5.0/out/client/debugger/PythonProcess.js:274:20)
    at PythonDebugger.pauseRequest (/Users/Jagan/.vscode/extensions/donjayamanne.python-0.5.0/out/client/debugger/Main.js:522:28)
    at PythonDebugger.DebugSession.dispatchRequest (/Users/Jagan/.vscode/extensions/donjayamanne.python-0.5.0/node_modules/vscode-debugadapter/lib/debugSession.js:400:22)
    at PythonDebugger.ProtocolServer._handleData (/Users/Jagan/.vscode/extensions/donjayamanne.python-0.5.0/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/Jagan/.vscode/extensions/donjayamanne.python-0.5.0/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

**Comment by TomIsPrettyCool** [comment]
Getting a very similar error when attempting do debug Flask apps on Windows.
`TypeError: Cannot read property 'Threads' of null
    at PythonDebugger.threadsRequest (C:\Users\TomsL\.vscode\extensions\donjayamanne.python-0.5.0\out\client\debugger\Main.js:309:27)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\TomsL\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\debugSession.js:418:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\TomsL\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\TomsL\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20): Error: TypeError: Cannot read property 'Threads' of null`

The error in the debug console is:
`ValueError: source code string cannot contain null bytes`

**Comment by DonJayamanne** [comment]
@jeswaran 
Please could you try this with the latest update (version 0.5.2) and let me know how it goes.
If problem persists, please send the following:
- remote version of python  
- sample python code being debugged  
- Error displayed in console
