### ISSUE TITLE
Debugging Error: "TypeError: Cannot read property "join" of undefined.

### ISSUE THREAD

**Issue by sunilkr** [DonJayamanne/pythonVSCode#486]
I am having issues with setting up debugging.

Following is my setup:
 _launch.json_
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "request": "launch",
            "name": "Python",
            "type": "python",
            "cwd": "${workspaceRoot}",
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "args": [],
            "stopOnEntry": false,
            "console": "integratedTerminal"
        }
    ]
}
```
_settings.json_
```json
{
    "python.pythonPath": "C:/Python27/python.exe"
}
```
_test.py_

```python
def main():
    print "OK"

if __name__ == '__main__':
    import sys
    sys.exit(int(main() or 0))
```

When I "Start debugging" (F5), i get following pop message along with option to open launch.json.
**TypeError: Cannot read property 'join' of undefined.**

"Run Python in terminal" works fine.

Following is the top of developer console log.

```
messageService.ts:128
TypeError: Cannot read property 'join' of undefined
    at PythonDebugger.launchRequest (C:\Users\TEST\.vscode\extensions\donjayamanne.python-0.5.0\out\client\debugger\Main.js:147:50)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\TEST\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\debugSession.js:358:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\TEST\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\TEST\.vscode\extensions\donjayamanne.python-0.5.0\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
```

Install:
OS: WIndows 7 x64 SP1
VSCode: 1.7.1
Node: 6.5.0
pythonVSCode: 0.5.0

**Comment by DonJayamanne** [comment]
@sunilkr 
I'll be publishing a new version of the extension, please try that out. If propblem persiss, please provide the errors from the developer console log. Thanks.

**Comment by sunilkr** [comment]
I am getting same message after the update also (0.5.2)
Full track is as follows.

```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90 TypeError: Cannot read property 'join' of undefined
    at PythonDebugger.launchRequest (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\out\client\debugger\Main.js:147:50)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\debugSession.js:361:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20): Error: TypeError: Cannot read property 'join' of undefined
    at PythonDebugger.launchRequest (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\out\client\debugger\Main.js:147:50)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\debugSession.js:361:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\sunil_kumar\.vscode\extensions\donjayamanne.python-0.5.2\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
    at Object.f [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:20675)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:121:27301
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:10797)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:14302)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:14982)
    at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:12805)
    at then (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:16432)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:12874)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _setCompleteValue (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:31:15317)e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90
```

**Comment by lookoutjames** [comment]
I have also just come across this error, with the newest version of the python extension. My `launch.json` file had not specified any `debugOptions` in the configuration, which seems to be the issue: adding `"debugOptions": []` to the configuration makes this error go away.

**Comment by DonJayamanne** [comment]
@sunilkr Are you still experiencing this issue? Please reopen if you are.
