### ISSUE TITLE
It fails to call Python when space in "python.pythonPath"

### ISSUE THREAD

**Issue by hanbaobao2005** [DonJayamanne/pythonVSCode#494]
VS Code ver: 1.7.1
Extension ver: 0.5.0
I remembered that space in 'python.pythonPath' was work (Refer to https://github.com/DonJayamanne/pythonVSCode/issues/397#issuecomment-254740368)

But now, it prompts (It fails to locate python.exe):
![image](https://cloud.githubusercontent.com/assets/1937472/20058372/b0687bf8-a52b-11e6-9068-6e66d5f3b35f.png)

here is the configuration:
"python.pythonPath": "D:/Program Files (x86)/python3.5/python.exe"

Attached the error code in from debug console:
/D:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:126 Cannot read property 'isEmpty' of undefined: TypeError: Cannot read property 'isEmpty' of undefined
    at Promise (C:\Users\kzhang\.vscode\extensions\donjayamanne.python-0.5.0\out\client\providers\definitionProvider.js:30:36)
    at PythonDefinitionProvider.provideDefinition (C:\Users\kzhang\.vscode\extensions\donjayamanne.python-0.5.0\out\client\providers\definitionProvider.js:21:16)
    at d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:22015
    at d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:16809
    at new n.Class.derive._oncancel (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:12916)
    at Object.l [as asWinJsPromise] (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:16772)
    at e.provideDefinition (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:21969)
    at d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:30621
    at t._withAdapter (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:29463)
    at t.$provideDefinition (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:30583)

Thanks,

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/pull/428

**Comment by DonJayamanne** [comment]
Fixed, will be in next release

**Comment by hanbaobao2005** [comment]
@DonJayamanne Cool~! Thanks
