### ISSUE TITLE
MemoryError when autocompleting large custom libraries

### ISSUE THREAD

**Issue by yRefl3x** [DonJayamanne/pythonVSCode#509]
Python version: 2.7.12
wxPython version: 3.0.2.0
OS: Windows 10
VSCode version: 1.7.1
pythonVSCode version: 0.5.5

This is a blocker for me, I'm going to stick with 0.4.1 (it works in that version strangely) until that's resolved. This issue is also known over at the jedi repository, but it seems like a fix is going to take a while there.

![intellisensebug](https://cloud.githubusercontent.com/assets/15350550/20171386/b702ccaa-a730-11e6-8033-9a6c5d66f364.png)
"Wird geladen" is german for "loading".

## Output from console window

```
extensionHost.ts:255 [Extension Host] ---------------------------I.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255 [Extension Host] stderr jediProxyI.logExtensionHostMessage @ extensionHost.ts:255
extensionHost.ts:255 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 404, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 395, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 175, in _serialize_completions
    completions = script.completions()
  File "preview\jedi\jedi\api\__init__.py", line 169, in completions
    completions = completion.completions()
  File "preview\jedi\jedi\api\completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview\jedi\jedi\api\completion.py", line 167, in _get_context_completions
    completion_names += self._get_class_context_completions(is_function=False)
  File "preview\jedi\jedi\api\completion.py", line 251, in _get_class_context_completions
    next(names_dicts)
  File "preview\jedi\jedi\evaluate\representation.py", line 484, in names_dicts
    for scope in self.py__mro__():
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\representation.py", line 434, in py__mro__
    for cls in self.py__bases__():
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\representation.py", line 463, in py__bases__
    return list(chain.from_iterable(args.eval_args()))
  File "preview\jedi\jedi\evaluate\param.py", line 175, in eval_args
    return [self._evaluator.eval_element(el) for stars, el in self._split()]
  File "preview\jedi\jedi\evaluate\__init__.py", line 263, in eval_element
    return self._eval_element_if_evaluated(element)
  File "preview\jedi\jedi\evaluate\__init__.py", line 276, in _eval_element_if_evaluated
    return self._eval_element_cached(element)
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\__init__.py", line 280, in _eval_element_cached
    return self._eval_element_not_cached(element)
  File "preview\jedi\jedi\debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview\jedi\jedi\evaluate\__init__.py", line 306, in _eval_element_not_cached
    types = self.eval_trailer(types, trailer)
  File "preview\jedi\jedi\evaluate\__init__.py", line 404, in eval_trailer
    new_types |= self.find_types(typ, node)
  File "preview\jedi\jedi\evaluate\__init__.py", line 143, in find_types
    return f.find(scopes, attribute_lookup=not search_global)
  File "preview\jedi\jedi\debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview\jedi\jedi\evaluate\finder.py", line 100, in find
    names = self.filter_name(scopes)
  File "preview\jedi\jedi\evaluate\finder.py", line 228, in filter_name
    for names_dict, position in names_dicts:
  File "preview\jedi\jedi\evaluate\finder.py", line 126, in <genexpr>
    return ((n, None) for n in self.scope.names_dicts(search_global))
  File "preview\jedi\jedi\evaluate\representation.py", line 824, in names_dicts
    for star_module in self.star_imports():
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\representation.py", line 840, in star_imports
    new = imports.ImportWrapper(self._evaluator, name).follow()
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\imports.py", line 89, in follow
    types = importer.follow()
  File "preview\jedi\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\jedi\evaluate\imports.py", line 246, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "preview\jedi\jedi\evaluate\imports.py", line 336, in _do_import
    source = module_file.read()
MemoryError
```

**Comment by DonJayamanne** [comment]
This is an upstream issue as you have identified. Hence there is nothing I can do.
You can revert to the old version of jedi as follows, add The following to the settings.json file
```json
"python.devOptions":["USERELEASEAUTOCOMason
```
