### ISSUE TITLE
 Python Debugging #481 

### ISSUE THREAD

**Issue by mohantsa** [DonJayamanne/pythonVSCode#528]
am finding issue like Error: spawn EACCES . when debugging.

console log :

workbench.main.js:90 spawn EACCES: Error: spawn EACCES
    at Object.f [as create] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:29:20675)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:121:27301
    at Object.v [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:10797)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:14302)
    at _run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _chainedError (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:14982)
    at n (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:12805)
    at then (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:16432)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:12874)
    at _run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _setCompleteValue (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15317)

## Environment data
VS Code version:  1.7
Python Extension version:  
Python Version:   2.7 (anaconda)
OS and version:    xubuntu 16.10
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
1. Please could you try debugging the application as an external console application.
2. If that doesn't work, then I'd like you to debug it as an external console application with the ```sudo``` privileges.  
For this, please add the following into your ```launch.json```   
And debug the application using this debug configuration.
```json
{
            "name": "External Terminal/Console with Sudo",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "null",
            "console": "externalTerminal",
            "debugOptions": [
              "WaitOnAbnormalExit",
              "WaitOnNormalExit"
            ]
          },
```

**Comment by mohantsa** [comment]
i got this error# Debug adapter process has terminated unexpectedly

**Comment by mohantsa** [comment]
console message 

messageService.ts:128 Debug adapter process has terminated unexpectedlye.doShow @ messageService.ts:128
internal/process/warning.js:24 (node:29939) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limitprocess.on @ internal/process/warning.js:24
index.js:23 [uncaught exception]: Error: read ECONNRESETonError @ index.js:23
index.js:26 Error: read ECONNRESET
    at exports._errnoException (util.js:1026)
    at Pipe.onread (net.js:564)onError @ index.js:26
events.js:160 Uncaught Error: read ECONNRESET
messageService.ts:128 Debug adapter process has terminated unexpectedlye.doShow @ messageService.ts:128

**Comment by DonJayamanne** [comment]
Looks like the ports might be getting  blocked. Let me check this out and get back.

**Comment by matyasforian** [comment]
This is happening for me too, its because of this line:     

    "cwd": "null",

If you set it to some sensible value, like: 

    "cwd": "${workspaceRoot}",

then it will work. 
Its a bug in the latest plugin (0.5.5), When I create a new project and set a Python launch configuration, it will be set to null, thus it will not work.

**Comment by robodair** [comment]
I ran into the same issue when trying to debug using a virtualenvironment. I ended up pointing my config.python.pythonPath directly to the python executable and no longer had this error. (Previously I was getting the message "venv is a directory")

Did something change in how python paths are handled for debugging?
