### ISSUE TITLE
ImportError: No module named ptvsd.visualstudio_py_debugger when running debugger on Unit Test

### ISSUE THREAD

**Issue by mre** [DonJayamanne/pythonVSCode#543]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.3
Python Version: 2.7.10, 3.4.3  
OS and version: 10.11.6
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env.SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "null",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "cwd": "null",
            "console": "externalTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "null",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "null",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "null",
            "args": [],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "null",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.pythonPath": "${workspaceRoot}/venv3/bin/python"
}
```   
## Logs

Output from ```Python``` output panel  (for Python 2.7.10)
```
Traceback (most recent call last):
  File "/Users/mendler/.vscode/extensions/donjayamanne.python-0.5.3/pythonFiles/PythonTools/testlauncher.py", line 35, in <module>
    main()
  File "/Users/mendler/.vscode/extensions/donjayamanne.python-0.5.3/pythonFiles/PythonTools/testlauncher.py", line 11, in main
    from ptvsd.visualstudio_py_debugger import DONT_DEBUG, DEBUG_ENTRYPOINTS, get_code
ImportError: No module named ptvsd.visualstudio_py_debugger
```
Output from ```Python``` output panel  (for Python 3.4.3)
```
Traceback (most recent call last):
  File "/Users/mendler/.vscode/extensions/donjayamanne.python-0.5.3/pythonFiles/PythonTools/testlauncher.py", line 35, in <module>
    main()
  File "/Users/mendler/.vscode/extensions/donjayamanne.python-0.5.3/pythonFiles/PythonTools/testlauncher.py", line 11, in main
    from ptvsd.visualstudio_py_debugger import DONT_DEBUG, DEBUG_ENTRYPOINTS, get_code
ImportError: No module named 'ptvsd
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
--
```

## Actual behavior

Start of Debug session for selected unit test.

## Expected  behavior

Error output in ```Python``` output panel (see above). 

## Steps to reproduce:  
-  Go to unit test in Python project
-  Above the unit test, click on "Debug Test"

**Comment by DonJayamanne** [comment]
Lol, I thought I fixed that issue, Cleary I didn't. Will fix the asap.

**Comment by robsonpeixoto** [comment]
It's happen again.

```
Traceback (most recent call last):
  File "/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.4/pythonFiles/PythonTools/testlauncher.py", line 35, in <module>
    main()
  File "/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.4/pythonFiles/PythonTools/testlauncher.py", line 11, in main
    from ptvsd.visualstudio_py_debugger import DONT_DEBUG, DEBUG_ENTRYPOINTS, get_code
ImportError: No module named 'ptvsd'
```

**Comment by DonJayamanne** [comment]
That's odd, it works at my end.
As a temporary solution please could you install the ptvsd module.

**Comment by DonJayamanne** [comment]
@robsonpeixoto 
Dam, didn't check the pytest and nosetest. Apologies.
Will fix asap.

**Comment by DonJayamanne** [comment]
Will release a new build shortly as this is one of the new features of the release,

**Comment by markshao** [comment]
meet the same bug

**Comment by DonJayamanne** [comment]
What version and what are the logs

**Comment by DonJayamanne** [comment]
@mre, @robsonpeixoto
Are you two still experiencing this issue with the latest version

**Comment by mre** [comment]
@DonJayamanne works on my machine now. Thanks for fixing! :smiley:

**Comment by robsonpeixoto** [comment]
Working for me too

**Comment by DonJayamanne** [comment]
Thanks guys
