### ISSUE TITLE
Debug adapter process has terminated unexpectedly > Ubuntu with python3.4

### ISSUE THREAD

**Issue by codingyourlife** [DonJayamanne/pythonVSCode#55]
Maybe I am doing smth wrong but I read everything I could find and couldn't figure it out. The message doesn't really say much about the problem. The Task I've set up works with Python 3.4 (that's the output produced via Strg+Shift+B).
![nodebug](https://cloud.githubusercontent.com/assets/10122382/14061990/da8fbd22-f38f-11e5-8b54-c305077f6b0d.JPG)
![launch json](https://cloud.githubusercontent.com/assets/10122382/14061991/da92438a-f38f-11e5-8af1-06badbefa975.jpg)
![settings json](https://cloud.githubusercontent.com/assets/10122382/14061992/da95a584-f38f-11e5-8560-dcaff4faefe3.jpg)

**Comment by zkwolf** [comment]
I also meet this problem.
my env:
win10
vscode 0.10.11
python3.5
But when I download the vscode insider and run,the problem disappear.

**Comment by leesoh** [comment]
Same issue here.
* Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux
* Python 2.7.11+
* VS Code 1.0.0

**Comment by DonJayamanne** [comment]
Hi guys @leesoh and @codingyourlife , I've uploaded a new version of the extension. Please let me know if this has fixed the problem.

**Comment by codingyourlife** [comment]
Thanks a lot. I don't have the VM anymore with the failing VSCode project and I've moved away from using VSCode (Jupyter fitted better to my needs in ML). Maybe @leesoh can answer that or otherwise just close the issue  if you think it's fixed.

**Comment by ocomsoft** [comment]
I cannot test right now, but please don't close this issue. I will update and let you know as I had this issue.

**Comment by leesoh** [comment]
Same issue on Linux.

**Comment by leesoh** [comment]
```
workbench.main.js:87 Debug adapter process has terminated unexpectedlye.doShow @ workbench.main.js:87e.show @ workbench.main.js:87t.onServerExit @ workbench.main.js:83(anonymous function) @ workbench.main.js:83emitTwo @ events.js:105emit @ events.js:185ChildProcess._handle.onexit @ internal/child_process.js:204
workbench.main.js:87 Canceled: Error: Canceled
    at Object.E [as create] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:17647)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:104:23592
    at Object.p [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:16345)
    at Object.__dirname.undefined.F.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:19673)
    at __dirname.undefined.t.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:20994)
    at __dirname.undefined.t.Class.define._error (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:20511)
    at n (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:18216)
    at Object.p [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:16345)
    at Object.__dirname.undefined.F.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:19673)
    at __dirname.undefined.t.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:23:20994)e.doShow @ workbench.main.js:87e.show @ workbench.main.js:87(anonymous function) @ workbench.main.js:88__dirname.undefined.t.Class.define.done @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23__dirname.undefined.t.Class.define.then @ workbench.main.js:23__dirname.undefined.O.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._setCompleteValue @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23__dirname.undefined.t.Class.define.then @ workbench.main.js:23__dirname.undefined.O.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._setCompleteValue @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._error @ workbench.main.js:23n @ workbench.main.js:23__dirname.undefined.t.Class.define.then @ workbench.main.js:23__dirname.undefined.O.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define._setCompleteValue @ workbench.main.js:23p @ workbench.main.js:23__dirname.undefined.F.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define.cancel @ workbench.main.js:23__dirname.undefined.t.Class.derive._cancelAction @ workbench.main.js:23__dirname.undefined.R.enter @ workbench.main.js:23__dirname.undefined.t.Class.define._run @ workbench.main.js:23__dirname.undefined.t.Class.define.cancel @ workbench.main.js:23(anonymous function) @ workbench.main.js:83(anonymous function) @ workbench.main.js:83
workbench.main.js:32 WARNING: Promise with no error callback:undefined
workbench.main.js:32 Error: Promise did not implement oncancel(…)
```

**Comment by DonJayamanne** [comment]
@leesoh , at this stage I'm stumped. I can see that there's some code that' not hanling a callback
Unfortunately I'm unable to find this.
@leesoh , would you be able to debug this for me at your end? I can give you the necessary instructions.
Thanks.

**Comment by DonJayamanne** [comment]
I will give you @leesoh a set of filles, all you need to do is copy them into a directory and some  log files will be generated.

**Comment by leesoh** [comment]
Sure thing!

**Comment by DonJayamanne** [comment]
Ok, @leesoh thanks for your help. I've managed to make the necessary changes and here are the instructions and the files (zipped up).
_1.  Close VS Code_   
_2. Identify the location of VS Code Extensions_   
 + Open a Finder (explorer) window and go to your home directory ($HOME)
 + You will find your folders such as Desktop, Documents, etc
 + You need to turn on the ability to view Hidden Files and Folders
 + On ubuntu this is "File -> View -> Show Hidden Files"
 + Now go into the following directory ".vscode -> extensions -> donjayamanne.python..xxx"     

_3. Delete the "out" folder in the above "donjayamanne.pythonxxx" directory_
 + Don't worry, you can always delete the whole extension and re-install it (best you re-install after this process)   
 + Next take the "out" folder from the zip file and extract it into the above "donjayamanne.python..xx" directory     

_4. Start VS Code and start debugging_   
_5. In your home directory a file named "pythonExtLog.log" should be created_   
_6. Please upload that log file._   

FYI - I have tested this on a Ubuntu machine and works as expected (famous last words :))

Hopefully that'll give me the information I need.
Thanks
[out.zip](https://github.com/DonJayamanne/pythonVSCode/files/331311/out.zip)

**Comment by ocomsoft** [comment]
With Version 0.3.14 on Ubuntu 15.10 and Python 3.4 it fails the first time then works the second time.

**Comment by DonJayamanne** [comment]
That's great, @leesoh any  luck? Thanks

**Comment by DonJayamanne** [comment]
However I would rather wait for @leesoh to come back with his  results, as this has been an issue for a while for a couple of people.

**Comment by leesoh** [comment]
Didn't work on Windows and the Debian-based Linux machine I had been doing the testing with thus far is pretty critical at the moment so I stood up a fresh Ubuntu box, installed VS Code and your extension and, first run, had the issue. I replaced out, ran a simple python "hello world" and got the issue again. Here's the log.
```
0 Main.constructor()
1 Main.initializeRequest()
2 Main.launchRequest()
3 Main.startDebugServer()
4 Main.InitializeEventHandlers()
5 LocalDebugServer.Start()
6 Main.setExceptionBreakPointsRequest()
7 LocalDebugClient.LaunchApplicationToDebug()
8 LocalDebugClient.getPTVSToolsFilePath()
```

**Comment by DonJayamanne** [comment]
Thanks a lot @leesoh and sorry to trouble you this way. Its just that I have tested this on windows, mac and Ubuntu without any issues, and only a handful of you are getting this error.
If its ok with you will provide you with two more such zip files, and that should be it. Thanks, will upload the files some time tomorrow (in around 12 hours, cheers).

**Comment by DonJayamanne** [comment]
HI @leesoh , one last test.
I have two zip files, "out Working.zip" and out.zip. 
I believe "out Working.zip" will work (i.e. it contains a change), and out.zip contains will generate additional logging information.

Please could you try both files, I'm very sorry for the trouble. and once again thanks for your help.
[out Working.zip](https://github.com/DonJayamanne/pythonVSCode/files/333884/out.Working.zip)
[out.zip](https://github.com/DonJayamanne/pythonVSCode/files/333885/out.zip)

**Comment by leesoh** [comment]
out Working:
```
0 Main.constructor()
1 Main.initializeRequest()
2 Main.launchRequest()
3 Main.startDebugServer()
4 Main.InitializeEventHandlers()
5 LocalDebugServer.Start()
6 Main.setExceptionBreakPointsRequest()
7 LocalDebugClient.LaunchApplicationToDebug()
8 LocalDebugClient.getPTVSToolsFilePath()
9 LocalDebugClient.LaunchApplicationToDebug.before_launcherArgs
10 LocalDebugClient.LaunchApplicationToDebug.launcherArgs_WaitOnAbnormalExit,WaitOnNormalExit,RedirectOutput,/home/liam/Desktop/test/hi.py
11 LocalDebugClient.LaunchApplicationToDebug.after_args
12 LocalDebugClient.LaunchApplicationToDebug.this.args.externalConsole=false
```

**Comment by leesoh** [comment]
out.zip:
```
0 Main.constructor()
1 Main.initializeRequest()
2 Main.launchRequest()
3 Main.startDebugServer()
4 Main.InitializeEventHandlers()
5 LocalDebugServer.Start()
6 Main.setExceptionBreakPointsRequest()
7 LocalDebugClient.LaunchApplicationToDebug()
8 LocalDebugClient.getPTVSToolsFilePath()
9 LocalDebugClient.getPTVSToolsFilePath()-after_currentFileName
10 LocalDebugClient.getPTVSToolsFilePath()-before_tmp.dir
11 LocalDebugClient.getPTVSToolsFilePath()-after_tmp.dir
12 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_no_error
13 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_value_/home/liam/.vscode/extensions/donjayamanne.python-0.3.14/pythonFiles/PythonTools
14 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_before_fsExtra.copy
15 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_before_fsExtra.copy
16 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_before_fsExtra.copy
17 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_before_fsExtra.copy
18 LocalDebugClient.getPTVSToolsFilePath()-tmp.dir_before_fsExtra.copy
19 LocalDebugClient.getPTVSToolsFilePath()-fsExtra.copy_no_error
20 LocalDebugClient.getPTVSToolsFilePath()-fsExtra.copy_no_error
21 LocalDebugClient.getPTVSToolsFilePath()-fsExtra.copy_no_error
22 LocalDebugClient.getPTVSToolsFilePath()-fsExtra.copy_no_error
23 LocalDebugClient.getPTVSToolsFilePath()-fsExtra.copy_no_error
24 LocalDebugClient.getPTVSToolsFilePath()-Promise.all_resolved
25 LocalDebugClient.LaunchApplicationToDebug().getPTVSToolsFilePath_resolved
26 LocalDebugClient.prependShebangToPTVSFile
27 LocalDebugClient.prependShebangToPTVSFile.getShebangLines
28 LocalDebugClient.prependShebangToPTVSFile.getShebangLines.prependFile_no_error
29 LocalDebugClient.LaunchApplicationToDebug.before_launcherArgs
30 LocalDebugClient.LaunchApplicationToDebug.launcherArgs_WaitOnAbnormalExit,WaitOnNormalExit,RedirectOutput,/home/liam/Desktop/test/hi.py
31 LocalDebugClient.LaunchApplicationToDebug.after_args
32 LocalDebugClient.LaunchApplicationToDebug.this.args.externalConsole=false
```

**Comment by DonJayamanne** [comment]
Hi @leesoh, does the "out working" fix the issue. 
Doesn't look like it does.

**Comment by leesoh** [comment]
Both failed on first run :(

**Comment by DonJayamanne** [comment]
Sorry @leesoh , I'm going to have to make more changes to get additional logging. Hopefully this will be it and I can get to the bottom of this issue.

**Comment by leesoh** [comment]
No problem. Thanks for digging into this! I'm happy to help out where I can.

**Comment by DonJayamanne** [comment]
HI @leesoh , here's another zip file, please could you test this as well.
[out.zip](https://github.com/DonJayamanne/pythonVSCode/files/336107/out.zip)

**Comment by leesoh** [comment]
Error on first run
```
0 Main.constructor()
1 Main.initializeRequest()
2 Main.launchRequest()
3 Main.startDebugServer()
4 Main.InitializeEventHandlers()
5 LocalDebugServer.Start()
6 Main.setExceptionBreakPointsRequest()
7 LocalDebugClient.LaunchApplicationToDebug()
8 LocalDebugClient.getPTVSToolsFilePath()
9 LocalDebugClient.LaunchApplicationToDebug.before_launcherArgs
10 LocalDebugClient.LaunchApplicationToDebug.launcherArgs_WaitOnAbnormalExit,WaitOnNormalExit,RedirectOutput,/home/liam/Desktop/test/hi.py
11 LocalDebugClient.LaunchApplicationToDebug.after_args
12 LocalDebugClient.LaunchApplicationToDebug.this.args.externalConsole=false
13 LocalDebugClient.LaunchApplicationToDebug.pyProc.spawned
14 LocalDebugClient.LaunchApplicationToDebug(this.pyProc.resolve())
15 LocalDebugServer.on.data
16 LocalDebugServer.on.data
17 LocalDebugServer.on.data.before.HandleIncomingData
18 PythonProcess.HandleIncomingData.exTypeError: Cannot read property 'HandleIncomingData' of undefined
19 LocalDebugServer.on.data.before.HandleIncomingData.catch.exTypeError: Cannot read property 'HandleIncomingData' of undefined
```

**Comment by DonJayamanne** [comment]
Excellent, finally found where things are going wrong, hang in there for 2 minutes and I'll give you another one. Thanks and sorry for this.

**Comment by DonJayamanne** [comment]
Here's the new file, please try this 
[out.zip](https://github.com/DonJayamanne/pythonVSCode/files/336114/out.zip)

**Comment by leesoh** [comment]
Massive improvement. Ran it 20 times, failed on 13 and 15. Was hitting F5 every second or so though, so that could just be me. Ran it again 20 times waiting longer (1-2 seconds) and it failed once.

http://pastebin.com/wS5WABwe

**Comment by DonJayamanne** [comment]
Thanks, todays update will contain this fix. Thanks for your help @leesoh

**Comment by DonJayamanne** [comment]
Hi @leesoh , @ocomsoft , @zkwolf , @codingyourlife  (everyone) a new update has been released and this should fix the issue.

**Comment by DonJayamanne** [comment]
A big thank you to @leesoh , for helping me resolve this issue.

**Comment by leesoh** [comment]
Happy to help!

**Comment by DonJayamanne** [comment]
I believe this is closed, if this issue still persists please comment and reopen.

**Comment by Y75QMO** [comment]
I had this problem. Error "Debug adapter process has terminated unexpectedly".

The problem was in the **launch.json** file generated. The option **`"cwd": "null"`** produces the error. It was solved changing the option to **`"cwd": "${workspaceRoot}"`**.

In case it is useful for anybody encountering this problem, here is the complete working configuration:

		{
			"name": "External Terminal/Console",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${file}",
			"cwd": "${workspaceRoot}",
			"console": "externalTerminal",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit"
			]
		}
