### ISSUE TITLE
Python plugins error: command not found

### ISSUE THREAD

**Issue by ipfans** [DonJayamanne/pythonVSCode#550]
## Environment data
VS Code version:  1.7.2 
Python Extension version:  0.5.3
Python Version:   2.7.12
OS and version:    OSX 10.12.1
Your settings.json:   
```json
    // Python 2.7 Settings
    "python.pythonPath": "/Users/User/.pyenv/shims/python",
    "python.linting.flake8Path": "/Users/User/.pyenv/shims/flake8",
    "python.formatting.yapfPath": "/Users/User/.pyenv/shims/yapf",
    "python.unitTest.nosetestPath": "/Users/User/.pyenv/shims/nosetests",
    "python.linting.pydocStylePath": "/Users/User/.pyenv/shims/pydocstyle",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.formatting.provider": "yapf",
    "python.linting.pydocstyleEnabled": true,
    "python.unitTest.nosetestsEnabled": true,
    "python.formatting.formatOnSave": true,
```   
## Logs

Output from ```Console window``` (Help->Developer Tools menu)
```
messageService.ts:128command 'python.sortImports' not found: Error: command 'python.sortImports' not found
    at e._tryExecuteCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:61:8214)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:61:8053
    at then (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:17056)
    at e.executeCommand (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:61:8027)
    at t.run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:49:26492)
    at e.runAction (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:11719)
    at click (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:11489)
    at CallbacksRegistry.apply (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/electron.asar/renderer/api/remote.js:275:21)
    at emitThree (events.js:116:13)
e.doShow	@	messageService.ts:128
e.show	@	messageService.ts:107
(anonymous function)	@	contextmenuService.ts:105
done	@	winjs.base.raw.js:1378
e.runAction	@	contextmenuService.ts:105
click	@	contextmenuService.ts:88
apply	@	callbacks-registry.js:54
(anonymous function)	@	remote.js:275
emitThree	@	events.js:116
emit	@	events.js:194
```

## Actual behavior

Show error message: command 'python/sortImports' not found

## Expected  behavior

Sort imports with sortimport

## Steps to reproduce:  
-  Right click on opened py file
-  Click "Sort Imports"

**Comment by ipfans** [comment]
This issue can not reappear when I upgraded to v0.5.4.
