### ISSUE TITLE
Error when launching jupyter kernel : Command: strk, Id: 0, Python Trace: Traceback (most recent call last):

### ISSUE THREAD

**Issue by bernardocaldas** [DonJayamanne/pythonVSCode#554]
I get an error when trying to run a line in Jupyter. It seems to be looking for an env that doesn't exist, as my envs are:

automl                   /Users/***/anaconda/envs/automl
python2                  /Users/***/anaconda/envs/python2
root                  *  /Users/***/anaconda

I've tried changing the interpreter, without any luck...

## Environment data
VS Code version:  Version 1.7.2 (1.7.2)
Python Extension version:  Version 0.5.5
Python Version:   3.5 - Anaconda
OS and version:    Mac

Error Message: Command: strk, Id: 0, Python Trace: Traceback (most recent call last):
  File "/Users/***/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/PythonTools/ipythonServer.py", line 283, in start_processing
    cmd(self, id)
  File "/Users/***/.vscode/extensions/donjayamanne.python-0.5.5/pythonFiles/PythonTools/ipythonServer.py", line 370, in _cmd_strk
    kernelUUID = multiKernelManager.start_kernel(kernel_name=kernelName)
  File "/Users/***/anaconda/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/***/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/Users/***/anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/***/anaconda/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/***/anaconda/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Users/***/anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/***/anaconda/envs/python3/bin/python'

**Comment by bernardocaldas** [comment]
This is the result of jupyter kernelspec list
Available kernels:
  python3    /Users/caldasb/Library/Jupyter/kernels/python3

I think it's using the name of the kernel to look for an anaconda env. I created a symlink for python3 in the envs folder and it started working.

**Comment by DonJayamanne** [comment]
Have you configured the python interpreter in your settings.json as per the following: https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

If not, then please configure it.
