### ISSUE TITLE
Plugin crashes

### ISSUE THREAD

**Issue by random82** [DonJayamanne/pythonVSCode#57]
Windows 10 + Python 2.7

There was an error in the python extension. Error Traceback (most recent call last):
  File "completion.py", line 309, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 300, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 136, in _serialize_completions
    completions = script.completions()
  File "C:\Users\Dominik\.vscode\extensions\donjayamanne.python-0.3.1\pythonFiles\jedi\api\__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "C:\Users\Dominik\.vscode\extensions\donjayamanne.python-0.3.1\pythonFiles\jedi\api\__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "C:\Users\Dominik\.vscode\extensions\donjayamanne.python-0.3.1\pythonFiles\jedi\api\__init__.py", line 246, in _simple_complete
    for names_dict, pos in names_dicts:
  File "C:\Users\Dominik\.vscode\extensions\donjayamanne.python-0.3.1\pythonFiles\jedi\evaluate\finder.py", line 500, in global_names_dict_generator
    for names_dict in scope.names_dicts(True):
  File "C:\Users\Dominik\.vscode\extensions\donjayamanne.python-0.3.1\pythonFiles\jedi\evaluate\representation.py", line 720, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'

**Comment by feuerwelt** [comment]
Unfortunately I have the same `completion.py` issue :/

**Comment by thomastaylor312** [comment]
I am seeing errors on a Mac as well with "unexpected end of input" when trying to use autocompletion.

**Comment by DonJayamanne** [comment]
Hi, I have updated the extension with a new version.
Please could you re-test it, if it doesn't work. The issue is in the Jedi library used. 
If it still exists, then please report the issue on the following git repo:
https://github.com/davidhalter/jedi

**Comment by feuerwelt** [comment]
Now it works perfectly! Thanks! :)
