### ISSUE TITLE
Sort import not working on __init__.py file

### ISSUE THREAD

**Issue by robsonpeixoto** [DonJayamanne/pythonVSCode#585]
## Environment data
VS Code version: 1.8.0
Python Extension version:  0.5.5
Python Version:   2.7.12
OS and version:    Mac OS X - 10.12.1 - 16B2555
Your settings.json:   
```json
    // python
    "python.linting.pylintArgs": [
        "--disable=C0111,C0103"
    ],
```   
## Logs
Output from ```Python``` output panel  

The output is empty
![image](https://cloud.githubusercontent.com/assets/124390/21240872/ece6bb7a-c2eb-11e6-9824-3238ab13ccda.png)

Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] Uncaught Exception:  Error: Invalid patch string: Skipped 1 files
[Extension Host] Error: Invalid patch string: Skipped 1 files
    at diff_match_patch.patch_fromText (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/common/editor.js:224:19)
    at Object.getTextEditsFromPatch (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/common/editor.js:45:34)
    at child_process.exec (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/providers/importSortProvider.js:31:42)
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
Invalid patch string: Skipped 1 files: Error: Invalid patch string: Skipped 1 files
    at diff_match_patch.patch_fromText (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/common/editor.js:224:19)
    at Object.getTextEditsFromPatch (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/common/editor.js:45:34)
    at child_process.exec (/Users/robinho/.vscode/extensions/donjayamanne.python-0.5.5/out/client/providers/importSortProvider.js:31:42)
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

## Actual behavior
Should sort the import
## Expected  behavior
Do nothing
## Steps to reproduce:  
-  Open a `__init__.py` file
-  Call `Sort Imports` command

**Comment by DonJayamanne** [comment]
@robsonpeixoto apologies for the delay in responding to this issue. Are you still experiencing this issue.
If you are, please reopen this issue.

**Comment by ytimenkov** [comment]
@DonJayamanne After recent updates I've started seeing this as well.

### VS Code Info

VS Code version: Code 1.20.0 (c63189deaa8e620f650cc28792b8f5f3363f2c5b, 2018-02-07T17:09:39.780Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2793)|
|Memory (System)|15.91GB (0.84GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe c:\Users\iuutim\Source\dsf|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.18.1
language-gas-x86|bas|0.0.1
head-file-guard|bjr|0.0.2
gitlens|eam|8.0.0
python|ms-|2018.1.0
cpptools|ms-|0.14.6
PowerShell|ms-|1.5.1
vscode-icons|rob|7.19.0
cmake|twx|0.0.17
</details>


I run python 3.6 (32 bit) and issue appeared when I re-enabled pylint.

I've noticed that issue starts appearing after certain amount of lines and imports in the file.
When I remove one line (even in file-level docstring) problem disappears.
[__init__.txt](https://github.com/DonJayamanne/pythonVSCode/files/1706716/__init__.txt)

**Comment by nbara** [comment]
I'm experiencing the same issue.

**Comment by VelizarVESSELINOV** [comment]
The issue is real, please reopen the issue.

**Comment by maxbbender** [comment]
Also experiencing this issue!

**Comment by hzlmn** [comment]
It is actually a problem with isort. If you want isort to work on `__init__.py` files you can add  
```json
"python.sortImports.args": [ "-ns"] 
```
to your settings.

**Comment by wsantos** [comment]
FYI, the correct solution is

```
    "python.sortImports.args": [
        "-ns",
        "__init__.py"
    ],
```

**Comment by Tiedye** [comment]
I am now running into this issue as well.

**Comment by c4collins** [comment]
I also have this issue.
