### ISSUE TITLE
Error while converting pandas dataframe to SparkDataframe

### ISSUE THREAD

**Issue by MyPythonGitHub** [DonJayamanne/pythonVSCode#590]
Hi All,
             I am using Python 2.7.12.

            I am invoking a pyspark shell and within it I am converting a Pandas Dataframe into Spark Dataframe using the command: **spark_df = sqlCtx.createDataFrame(df_new)**

But I am unable to get past the following error. Please can you help me with it - it's a bit urgent:

Traceback (most recent call last):
  File "/home/c841407/alv/codes/score/single_fold_score_model_load.py", line 41, in <module>
    spark_df = sqlCtx.createDataFrame(df_new)
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/pyspark.zip/pyspark/sql/context.py", line 338, in createDataFrame
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1295, in first
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1277, in take
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/pyspark.zip/pyspark/context.py", line 897, in runJob
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/usr/hdp/2.3.2.0-2950/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 46, toplxhddp007.rails.rwy.bnsf.com): java.io.IOException: Cannot run program "python2.7": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.api.python.PythonWorkerFactory.startDaemon(PythonWorkerFactory.scala:160)
        at org.apache.spark.api.python.PythonWorkerFactory.createThroughDaemon(PythonWorkerFactory.scala:86)
        at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:62)
        at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:130)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:73)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 13 more

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1273)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1264)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1263)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1263)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:730)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:730)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1457)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1418)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48
-

**Comment by ItsAnkit** [comment]
Hey, have u resolved it?
I am facing the same issue while calling collect().
It is showing same Py4JJavaError, java.io.IOException Cannot run program /home/user/anaconda2/bin/python error=2 No such file or directory. But, i have installed anaconda2 in /opt directory instead of /home. So, can anyone help me out?

**Comment by DonJayamanne** [comment]
This isn't an issue with the extension, Please raise this issue on Stackoverflow or elsewhere for some better response.
