### ISSUE TITLE
Refactoring not working 

### ISSUE THREAD

**Issue by miuzel** [DonJayamanne/pythonVSCode#605]
## Environment data
VS Code version:  1.8.1
Python Extension version: 0.5.5  
Python Version:   2.7.10
OS and version:   Win7
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
extensionHost.ts:293[Extension Host] SyntaxError: Unexpected token C in JSON at position 0
    at dataStr.split.filter.map.resp (C:\Users\mingxuan.zhang\.vscode\extensions\donjayamanne.python-0.5.5\out\client\refactor\proxy.js:136:102)
    at Array.map (native)
    at RefactorProxy.handleStdError (C:\Users\mingxuan.zhang\.vscode\extensions\donjayamanne.python-0.5.5\out\client\refactor\proxy.js:136:85)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)A.logExtensionHostMessage @ extensionHost.ts:293
```

## Actual behavior
The rename textbox revealed 
the loading bar keep running after put the new name
Symbol not renamed

## Expected  behavior
Symbol renamed

## Steps to reproduce:  
select a symbol and try to rename it with F2

**Comment by hanpari** [comment]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:


I have same issue:
![vscode](https://cloud.githubusercontent.com/assets/7354817/21727096/e22936b2-d43f-11e6-8932-ee36531ea4de.png)

**Comment by drzunny** [comment]
maybe it's related to #579 and my PR ( #748 ) . You can try to convert your file to `CRLF`  to verify it.

**Comment by DonJayamanne** [comment]
This has been fixed in the latest version
