### ISSUE TITLE
Update: Now seems to be an address translation error. Error: Linter pylint is not installed. But pylint is already installed in Cygwin.

### ISSUE THREAD

**Issue by zinechant** [DonJayamanne/pythonVSCode#615]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.5
Python Version:   3.4.5 & 2.7.12
OS and version:   Windows 10. Cygwin. 
Your settings.json:   
```json
{
    // Columns at which to show vertical rulers
    "editor.rulers": [80],
    "editor.fontSize": 13,

    // Controls auto save of dirty files. Accepted values:  "off", "afterDelay", "onFocusChange" (editor loses focus), "onWindowChange" (window loses focus). If set to "afterDelay", you can configure the delay in "files.autoSaveDelay".
    "files.autoSave": "off"
}
```   
## Logs
Output from ```Python``` output panel  
```Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: spawn pylint ENOENT
```   
Output from ```Console window``` (Help->Developer Tools menu)
```messageService.ts:126Linter pylint is not installede.doShow @ messageService.ts:126
```

## Actual behavior
Pylint does not work well with python under Cygwin.
## Expected  behavior
Hope it can work.
In Cygwin:
```
$ pylint --version
No config file found, using default configuration
pylint 1.6.4,
astroid 1.4.8
Python 3.4.5 (default, Oct 10 2016, 14:41:48)
[GCC 5.4.0]
```
If press 'install pylint' in the pop-up messages, the following are shown in the terminal.
```
C:\ProgramData\Cygwin64\home\Zine.Chant\10x10-uap\src\hardware_models\RTL\UDPLane>python -m pip install pylint
Requirement already satisfied: pylint in /usr/lib/python3.4/site-packages
Requirement already satisfied: astroid<1.5.0,>=1.4.5 in /usr/lib/python3.4/site-packages (from pylint)
Requirement already satisfied: mccabe in /usr/lib/python3.4/site-packages (from pylint)
Requirement already satisfied: isort>=4.2.5 in /usr/lib/python3.4/site-packages (from pylint)
Requirement already satisfied: six in /usr/lib/python3.4/site-packages (from pylint)
Requirement already satisfied: wrapt in /usr/lib/python3.4/site-packages (from astroid<1.5.0,>=1.4.5->pylint)
Requirement already satisfied: lazy-object-proxy in /usr/lib/python3.4/site-packages (from astroid<1.5.0,>=1.4.5->pylint)
```

**Comment by zinechant** [comment]
Tried to specify the full path in settings.json:
json```    // Path to Python, you can use a custom version of Python by modifying this setting to include the full path.
    "python.pythonPath": "C:\\ProgramData\\Cygwin64\\bin\\python3",

    // Path to Pylint, you can use a custom version of pylint by modifying this setting to include the full path.
    "python.linting.pylintPath": "C:\\ProgramData\\Cygwin64\\bin\\pylint",
```
Got the same error. Output of python panel:
```Linting with pylint failed.
You could either install the 'pylint' linter or turn it off in setings.json via "python.linting.pylintEnabled = false".
Error: spawn C:\ProgramData\Cygwin64\bin\pylint ENOENT
```

**Comment by zinechant** [comment]
As pointed in another similar thread, pylint is a python script.
Tried the following as well in settings.json:
```json
    // Path to Python, you can use a custom version of Python by modifying this setting to include the full path.
    "python.pythonPath": "C:\\ProgramData\\Cygwin64\\bin\\python3",

    // Path to Pylint, you can use a custom version of pylint by modifying this setting to include the full path.
    "python.linting.pylintPath": "C:\\ProgramData\\Cygwin64\\bin\\python3",

    // Arguments passed in. Each argument is a separate item in the array.
    "python.linting.pylintArgs": ["C:\\ProgramData\\Cygwin64\\bin\\pylint"],
```
No errors pop up, but there are errors in the python panel of output:
```
##########Linting Output - pylint##########

No config file found, using default configuration
Traceback (most recent call last):
  File "C:\ProgramData\Cygwin64\bin\pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/lib/python3.4/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/pylint/lint.py", line 1310, in __init__
    linter.check(args)
  File "/usr/lib/python3.4/site-packages/pylint/lint.py", line 732, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python3.4/site-packages/pylint/lint.py", line 863, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/usr/lib/python3.4/site-packages/pylint/lint.py", line 922, in check_astroid_module
    tokens = utils.tokenize_module(ast_node)
  File "/usr/lib/python3.4/site-packages/pylint/utils.py", line 141, in tokenize_module
    with module.stream() as stream:
  File "/usr/lib/python3.4/site-packages/astroid/scoped_nodes.py", line 389, in stream
    return self._get_stream()
  File "/usr/lib/python3.4/site-packages/astroid/scoped_nodes.py", line 374, in _get_stream
    stream = open(self.source_file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/Zine.Chant/10x10-uap/src/hardware_models/RTL/UDPLane/c:\\ProgramData\\Cygwin64\\home\\Zine.Chant\\10x10-uap\\src\\hardware_models\\RTL\\UDPLane\\test\\src\\GetCases.py'
```

**Comment by DonJayamanne** [comment]
Duplicate #194

**Comment by BillDenton** [comment]
I had a similar problem in Windows (not cgywin) when opening a python the error message about pylint not being installed appear. After installing pylint the error message still appear. I fixed it by changing the pythonPath:
"python.pythonPath": "C:\\Python27\\python"
"C:\Python27" was already on the Windows path.
