### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by zeus** [DonJayamanne/pythonVSCode#626]
## Environment data
VS Code version:  1.8.1
Python Extension version: 0.5.5  
Python Version:   2.7.13
OS and version:    Windows 10
Your launch.json (if dealing with debugger issues):  
```json
        {
        
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 4000,
            "secret": "my_secret",
            "host":"localhost"
        }
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
None
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
index.js:22 [uncaught exception]: Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\out\client\debugger\Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\debugSession.js:421:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)onError @ index.js:22(anonymous function) @ index.js:91emitOne @ events.js:96emit @ events.js:188window.onerror @ C:\Program Files (x86)\Microsoft VS Code\resources\electron.asar\renderer\init.js:120i.globals.onerror @ errorTelemetry.ts:64
index.js:25 Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\out\client\debugger\Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\debugSession.js:421:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\zeus\.vscode\extensions\donjayamanne.python-0.5.5\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:21136
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18089)
    at _error (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17606)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1178
    at _.e.dispatch (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2523)
    at _.e.handleData (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2035)
    at Socket.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1038)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

## Actual behavior
Debug adapter process has terminated unexpectedly

## Expected  behavior
Attach to simple process

## Steps to reproduce:  
- Simple program:
```
#!/usr/bin/env python
import ptvsd
ptvsd.enable_attach("my_secret", address=('0.0.0.0', 4000))
ptvsd.wait_for_attach()
t = 1+1
``` 
- Run
- Run Debug, failed

## Other
Connected from MS VS 2015 successfully.
Can't connect from VSC with 'attach' option. 'Launch' works fine.

**Comment by zeus** [comment]
VS Code version: 1.9.1
Python Extension version: 0.5.8

Nothig changed. Is there any ideas where to dig into?

**Comment by dholth** [comment]
I have also had trouble remote debugging a vagrant vm. Even after opening and forwarding the port in the firewall. Sometimes it works consistently and sometimes it fails. It seems to work more reliably when remote debugging a program running on the same machine.

Experiments

`ptvsd.enable_attach(None, ...) # no secret. set secret: "" in launch.json`

The first time I removed the secret, it worked. I thought I had fixed it, but then it stopped working again.

`time.sleep(1); ptvsd.wait_for_attach() # could there be a race condition?`

`print secret # in ptvsd/attach_server.py` somehow, this also fixed the problem for a little while.

There was something in attach_server suggesting the secret might confuse things when the remote process is behind a NAT (debugger connects to 127.0.0.1, but debugged sees connection from 10.)...

Mysterious.

**Comment by zeus** [comment]
Just upgraded to extension 0.5.9 and vsc 1.10.1

Now i've got this in console:

```
Unhandled exception in thread started by <bound method DebuggerLoop.loop of <ptvsd.visualstudio_py_debugger.DebuggerLoop object at 0x0000000003826898>>
PS C:\Users\zeus\OneDrive\coding\big_fat\ostankino_crm> python .\vscdebug_test.py
Unhandled exception in thread started by
sys.excepthook is missing
lost sys.stderr
```

**Comment by itowlson** [comment]
I am seeing this issue when I specify a secret in `enable_attach`.  Without a secret, the debugger attaches to the remote server and all is well.  With a secret, I get the `Debug adapter process has terminated unexpectedly` error.

I don't see the console log messages other users have mentioned.  However, I am using Kubernetes port forwarding to connect localhost:3000 to the remote port 3000, and Kubernetes reports the following error, which reads like the target process is rejecting the request with the secret.

```
E0310 15:38:12.157798   12360 portforward.go:314] error copying from local connection to remote stream: read tcp4 127.0.0.1:3000->127.0.0.1:60994: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by itowlson** [comment]
Per @dholth's comment, I'm on a corporate network (and connecting via the port forwarder), so this could be related.  However, it works when I run the PTVS debugger from _within_ Visual Studio 2015, so it's not solely a network configuration issue.

**Comment by GiuseppeLaurenza** [comment]
i do not know if is better to open another issue, but I have the same problem with pool.map instruction

`def foo(arg):
    print arg
if __name__ == '__main__':
    list_files = ["a", "b", "c"]
    pool = Pool(processes=(cpu_count() - 1))
    pool.map(foo, list_files)`

using debugger of other IDE (like pycharm) and debug in terminal with pdb, I have not any problem

**Comment by WasabiFan** [comment]
I am seeing the same issue. The log is available [here](https://gist.github.com/WasabiFan/985125afb1d6eabba6bbff90e2492f6c). This seems to happen regardless of whether I have a secret configured.

**Comment by zWaR** [comment]
I am also getting this problem. The log in the Console is:

```
Debug adapter process has terminated unexpectedly
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
g.onServerExit @ rawDebugSession.ts:517
(anonymous) @ rawDebugSession.ts:431
emitTwo @ events.js:111
emit @ events.js:191
__dirname.ChildProcess._handle.onexit @ internal/child_process.js:215
```

**Comment by zWaR** [comment]
In the python output panel I have the following error:
```
----------Generating Tags----------
ctags --options=/Users/nojvek/.vscode/extensions/donjayamanne.python-0.5.9/resources/ctagOptions --languages=Python --exclude=/site-packages/ -o /Users/nojvek/mp/analytics/.vscode/tags .
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...
```
I was able to fix this by installing ctags with homebrew:
`brew install ctags`

However this does not stop debugger from crashing when attaching to a remote end.

**Comment by bpartridge** [comment]
Also getting this problem on Mac. It seems `this.pythonProcess` is being cleared, but other callbacks are assuming it exists, thus the "Threads of undefined" errors. The root cause of the early clearing may be related to this type of error:

```
messageService.ts:125 There was an error in starting the debug server. Error = {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"127.0.0.1","port":8030}
```

Interestingly, telnetting into that port also fails to receive anything. Is there documentation on the raw protocol? It's possible that something's broken on the PTVSD side, or we're connecting wrong somehow...

**Comment by etchen99** [comment]
I am also running into this issue on OSX.  extension version 0.6.4.  I get the ctags output message in the Python output window and the messageService error on the Console, but nothing all that useful.

**Comment by Kenuat** [comment]
Same problem here, Windows 8.1 latest versions of Code and extension, verbose output:

> Debug adapter process has terminated unexpectedly
> e.doShow @ messageService.ts:125
> e.show @ messageService.ts:104
> g.onServerExit @ rawDebugSession.ts:517
> (anonymous) @ rawDebugSession.ts:431
> emitTwo @ events.js:111
> emit @ events.js:191
> __dirname.ChildProcess._handle.onexit @ internal/child_process.js:215

**Comment by mostafaeweda** [comment]
I'm hitting the same issue

**Comment by mostafaeweda** [comment]
@DonJayamanne I'm using version 3.0.0 and still hitting various attach issues (including this) - will include stack traces when I hit it again.

**Comment by marcosfede** [comment]
Using version 3.0.0 of ptvsd, trying to connect shows `Debug adapter process has terminated unexpectedly `
my launch.json is 
```
        {
            "name": "Attach Docker (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/code",
            "port": 3000,
            "secret": "",
            "host": "localhost"
        }
```

**Comment by royrwood** [comment]
I'm also having problems, even with v3.0.0 of ptvsd.

I can connect to my remote Python app, but stepping through the code is erratic. Breakpoints are skipped, and single-stepping results in multiple lines executed.

Eventually the remote process dies and prints this to console:

    Unhandled exception in thread started by 
    sys.excepthook is missing
    lost sys.stderr

This is running on an Ubuntu 16.10 system, VS 1.15.1, ptvsd 3.0.0.

Visual Studio Code version:
=====================
Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17:16:27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

launch.json:
=========
        {
            "name": "Attach (localhost 1337)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/home/rrwood/Python/debug_test",
            "port": 1337,
            "secret": "secret",
            "host": "localhost"
        }

Sample code:
===========
from __future__ import print_function
import ptvsd
print('Waiting for remote debugger connection...')
ptvsd.enable_attach('secret', address=('0.0.0.0', 1337))
ptvsd.wait_for_attach()
print('Remote debugger connected.')

print('Hello, world.')

max_val = 5

for i in range(1, max_val):
    print('i = ', i)

Output:
======
$ python count.py 
Waiting for remote debugger connection...
Remote debugger connected.
Hello, world.
i =  1
i =  2
i =  3
i =  4
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#71
