### ISSUE TITLE
Unable to use Run cell in Jupyter example

### ISSUE THREAD

**Issue by Kim-SeongCheol** [DonJayamanne/pythonVSCode#664]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6 
Python Version:   2.7.11(Anaconda 2.5.0 64 bit)
OS and version:    Windows 7
## Actual behavior
I pasted a standard plot sample code in Jupyter exeample. then executed it by using Run Cell 

#%%
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np

x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show() 

I got following error.

>Error Message: Command: lsks, Id: 23, Python Trace: Traceback (most recent call last):
  File "C:\Users\Administrator\.vscode\extensions\donjayamanne.python-0.5.6\pythonFiles\PythonTools\ipythonServer.py", line 283, in start_processing
    cmd(self, id)
  File "C:\Users\Administrator\.vscode\extensions\donjayamanne.python-0.5.6\pythonFiles\PythonTools\ipythonServer.py", line 354, in _cmd_lstk
    kernelspecs = json.dumps(listKernelSpecs())
  File "C:\Users\Administrator\.vscode\extensions\donjayamanne.python-0.5.6\pythonFiles\PythonTools\ipythonServer.py", line 95, in listKernelSpecs
    return kernelSpecManager.get_all_specs()
AttributeError: 'KernelSpecManager' object has no attribute 'get_all_specs'

But, when i executed by debug, it works well.

Your settings.json:   
```json
```   {
    "python.pythonPath": "C:/Anaconda2/python.exe"
}

**Comment by DonJayamanne** [comment]
Is this still an issue. Please reopen if it is

**Comment by casbby** [comment]
i have the same problem. the project is shared between mac and PC. i didnt have problem on mac. it only happened on windows.any advise?
