### ISSUE TITLE
Prospector not working in Git view

### ISSUE THREAD

**Issue by TimonVS** [DonJayamanne/pythonVSCode#665]
## Environment data
VS Code version:  1.8.1
Python Extension version:  
Python Version:  3.5.2
OS and version:  macOS Sierra (10.12.1)

## Actual behavior

When I open the Git overview in VS Code I get an error that there was an error running Prospector.

![https://i.imgur.com/1PEIddy.png](https://i.imgur.com/1PEIddy.png)

## Steps to reproduce:  
-  Enable Prospector in settings.json
-  Open a Git-enabled project, make changes to Python code and open the Git overview

## Settings  

Your settings.json:   
```json
{
  "python.linting.pylintEnabled": false,
  "python.linting.prospectorEnabled": true,
  "python.linting.prospectorArgs": [
    "--strictness=high"
  ]
}
```   
## Logs
Output from ```Python``` output panel  
```
Linting with prospector failed.
Command failed: prospector --strictness=high --absolute-paths --output-format=json /209
Traceback (most recent call last):
  File "/Users/timon/anaconda3/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/Users/timon/anaconda3/lib/python3.5/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/Users/timon/anaconda3/lib/python3.5/site-packages/prospector/run.py", line 49, in execute
    self.config.explicit_file_mode, self.config.workdir)
  File "/Users/timon/anaconda3/lib/python3.5/site-packages/prospector/finder.py", line 201, in find_python
    files, modules, directories, packages = _find_paths(ignores, paths[0], paths[0])
  File "/Users/timon/anaconda3/lib/python3.5/site-packages/prospector/finder.py", line 144, in _find_paths
    for filename in os.listdir(curpath):
FileNotFoundError: [Errno 2] No such file or directory: '/209'
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
messageService.ts:126 There was an error in running the linter 'prospector'
```

**Comment by ibigpapa** [comment]
I'm also seeing same result.
Plugin version 0.5.6
VScode version 1.8.1
```
Linting with prospector failed.
Command failed: prospector --absolute-paths --output-format=json /37
Traceback (most recent call last):
  File "/home/troy_harrison/anaconda3/envs/paa/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/home/troy_harrison/anaconda3/envs/paa/lib/python3.5/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/home/troy_harrison/anaconda3/envs/paa/lib/python3.5/site-packages/prospector/run.py", line 49, in execute
    self.config.explicit_file_mode, self.config.workdir)
  File "/home/troy_harrison/anaconda3/envs/paa/lib/python3.5/site-packages/prospector/finder.py", line 201, in find_python
    files, modules, directories, packages = _find_paths(ignores, paths[0], paths[0])
  File "/home/troy_harrison/anaconda3/envs/paa/lib/python3.5/site-packages/prospector/finder.py", line 144, in _find_paths
    for filename in os.listdir(curpath):
FileNotFoundError: [Errno 2] No such file or directory: '/37'
```

**Comment by DonJayamanne** [comment]
What is the ```git overview```

**Comment by TimonVS** [comment]
@DonJayamanne I mean the compare view in the Git view.
Example from another project: ![https://i.imgur.com/v00Wa31.png](https://i.imgur.com/v00Wa31.png)

**Comment by DonJayamanne** [comment]
Got it, thanks

**Comment by zioroboco** [comment]
I'm still getting this bug. Linter throws a FileNotFoundError, but the fix is checking for OSError as a string.

VS Code version: 1.10.2
Extension version: 0.6.0

Output:
```
Linting with prospector failed.
Command failed: prospector --absolute-paths --output-format=json /4
Traceback (most recent call last):
  File "/usr/local/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/usr/local/lib/python3.6/site-packages/prospector/run.py", line 49, in execute
    self.config.explicit_file_mode, self.config.workdir)
  File "/usr/local/lib/python3.6/site-packages/prospector/finder.py", line 201, in find_python
    files, modules, directories, packages = _find_paths(ignores, paths[0], paths[0])
  File "/usr/local/lib/python3.6/site-packages/prospector/finder.py", line 144, in _find_paths
    for filename in os.listdir(curpath):
FileNotFoundError: [Errno 2] No such file or directory: '/4'
```

**Comment by jeffbmartinez** [comment]
I'm seeing a similar issue. My error message comes up even if I don't switch to the VSCode Source Control panel. It comes up at startup or just about any time I save a .py file.

# System setup

* OSX 10.11.6 (el capitan)
* Visual Studio Code Version 1.11.1 (1.11.1)
* pythonVSCode version 0.6.0.
* Calling `code .` inside a virtual environment created with `python3 -m venv`
* Python 3.6.1
* Prospector 0.12.4
* Git version 2.12.2

# Relevant VSCode settings

```
{
    "python.linting.prospectorEnabled": true,
    "python.linting.pylintEnabled": false
}
```

# The error message

I replaced the full file paths with an abbreviated `/.../prdashboard/...`

Of special note is the `.git` appended in the `/.../prdashboard/collector.py.git` filename. This makes me think it's related to the errors being seen in previous comments.

```
Linting with prospector failed.
Command failed: prospector --absolute-paths --output-format=json /.../prdashboard/collector.py.git
Traceback (most recent call last):
  File "/.../prdashboard/bin/prospector", line 11, in <module>
    load_entry_point('prospector==0.12.4', 'console_scripts', 'prospector')()
  File "/.../prdashboard/lib/python3.6/site-packages/prospector/run.py", line 165, in main
    prospector.execute()
  File "/.../prdashboard/lib/python3.6/site-packages/prospector/run.py", line 49, in execute
    self.config.explicit_file_mode, self.config.workdir)
  File "/.../prdashboard/lib/python3.6/site-packages/prospector/finder.py", line 201, in find_python
    files, modules, directories, packages = _find_paths(ignores, paths[0], paths[0])
  File "/.../prdashboard/lib/python3.6/site-packages/prospector/finder.py", line 144, in _find_paths
    for filename in os.listdir(curpath):
FileNotFoundError: [Errno 2] No such file or directory: '/.../prdashboard/collector.py.git'
```

**Comment by DonJayamanne** [comment]
I believe this has been fixed, please reopen if it still persists.
