### ISSUE TITLE
TypeError: Cannot read property 'Threads' of null

### ISSUE THREAD

**Issue by spike-spb** [DonJayamanne/pythonVSCode#677]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   2.7
OS and version:    Linux 64 bit

## Actual behavior
Debugger terminates

## Expected  behavior
Debugger works

## Steps to reproduce
I am trying to debug a Django app. 
Running vscode from virtualenv (see settings).
I place several brakepoints -> debugger terminates during request to server.
If I don't place breakpoints -> debugger runs.

## Settings  
Your launch.json (if dealing with debugger issues):  
I use "Django" configuration.
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${file}",
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		},
		{
			"name": "Python Console App",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${file}",
			"externalConsole": true,
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit"
			]
		},
		{
			"name": "Django",
			"type": "python",
			"request": "launch",
			"stopOnEntry": false,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${workspaceRoot}/manage.py",
			"args": [
				"runserver",
				"--noreload"
			],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput",
				"DjangoDebugging"
			]
		},
		{
			"name": "Django UnitTest",
			"type": "python",
			"request": "launch",
			"stopOnEntry": false,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${workspaceRoot}/manage.py",
			"args": [
				"test"
			],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput",
				"DjangoDebugging"
			]
		},
		{
			"name": "Watson",
			"type": "python",
			"request": "launch",
			"stopOnEntry": true,
			"pythonPath": "${config.python.pythonPath}",
			"program": "${workspaceRoot}/console.py",
			"args": [
				"dev",
				"runserver",
				"--noreload=True"
			],
			"debugOptions": [
				"WaitOnAbnormalExit",
				"WaitOnNormalExit",
				"RedirectOutput"
			]
		},
		{
			"name": "Attach",
			"type": "python",
			"request": "attach",
			"localRoot": "${workspaceRoot}",
			"remoteRoot": "${workspaceRoot}",
			"port": 3000,
			"secret": "my_secret",
			"host": "localhost"
		}
	]
}
```   
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.DS_Store": true,
		"**/node_modules": true,
		"**/bower_components": true,
		"build": true
	},
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
		"**/build": true,
		"**/main.js": true,
		"**/libs.js": true,
		"**/lib": true
	},
	"python.pythonPath": "/home/leonid/.envs/myproject/bin/python",
	"python.linting.pylintEnabled": false,
	"python.linting.flake8Enabled": true,
	"python.linting.enabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
[27/Jan/2017 11:55:10] "GET /static/lib/elfinder/js/jquery.dialogelfinder.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/fancytree-2.4.1/dist/jquery.fancytree-all.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/bower_components/vega-elfinder/dist/vega-elfinder.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/bower_components/vg-required-mark/dist/vg-required-mark.min.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/css/ng-table.min.css.map HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/js/main.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/angular-locale_ru-ru.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/js/jquery.browser.min.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/elfinder/js/elfinder.full.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/elfinder/js/i18n/elfinder.ru.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/elfinder/js/jquery.dialogelfinder.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:10] "GET /static/lib/fancytree-2.4.1/dist/jquery.fancytree-all.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:11] "GET /static/bower_components/vega-elfinder/dist/vega-elfinder.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:11] "GET /static/bower_components/vg-required-mark/dist/vg-required-mark.min.js HTTP/1.1" 304 0
[27/Jan/2017 11:55:11] "GET /new_api/source-types HTTP/1.1" 200 1899
[27/Jan/2017 11:55:11] "GET /new_api/tasks/status-types HTTP/1.1" 200 1772
[27/Jan/2017 11:55:11] "GET /new_api/operation-types/raster_input HTTP/1.1" 200 309
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
TypeError: Cannot read property 'Threads' of null
    at PythonDebugger.threadsRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/out/client/debugger/Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20): Error: TypeError: Cannot read property 'Threads' of null
    at PythonDebugger.threadsRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/out/client/debugger/Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
    at file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:21136
    at Object.v [as _notify] (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
    at _run (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18089)
    at _error (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17606)
    at file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1178
    at _.e.dispatch (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2523)
    at _.e.handleData (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2035)
    at Socket.<anonymous> (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1038)
    at emitOne (events.js:96:13)
TypeError: Cannot read property 'Threads' of null
    at PythonDebugger.threadsRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/out/client/debugger/Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20): Error: TypeError: Cannot read property 'Threads' of null
    at PythonDebugger.threadsRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/out/client/debugger/Main.js:321:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/leonid/.vscode/extensions/donjayamanne.python-0.5.6/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
    at file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:90:21136
    at Object.v [as _notify] (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:13263)
    at Object.enter (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16768)
    at _run (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:18089)
    at _error (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17606)
    at file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1178
    at _.e.dispatch (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2523)
    at _.e.handleData (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:2035)
    at Socket.<anonymous> (file:////home/leonid/sdk/VSCode-linux-x64/resources/app/out/vs/workbench/electron-browser/workbench.main.js:85:1038)
    at emitOne (events.js:96:13)
```

**Comment by DonJayamanne** [comment]
@spike-spb  Please could you provide the sample code (or link to Git repo). Looks like the application you're debugging has crashed.
Please do provide necessary instructions to replicate the issue.

**Comment by DonJayamanne** [comment]
Please reopen if problem persists
