### ISSUE TITLE
Debugger "release unlocked lock"

### ISSUE THREAD

**Issue by staffann** [DonJayamanne/pythonVSCode#683]
## Environment data
VS Code version:  
1.8.1

Python Extension version:  
0.5.6

Python Version:   
3.4.3

OS and version:    
Ubunto 14.04

## Actual behavior
Exeception when stepping in the debugger: "release unlocked lock"

## Expected  behavior
No exception!

## Steps to reproduce:  
- Set a breakpoint
-  Start the program
-  When stopped at the breakpoint, step inside the code. Possible step quickly (not sure it is relevant, but it might be)

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Hypnotoad",
            "type": "python",
            "pythonPath":"${config.python.pythonPath}",
            "request": "launch",
            "stopOnEntry": true,
            "console": "none",
            "program": "${workspaceRoot}/xxxxxx/main.py",
            "args": ["${workspaceRoot}/fulltests/recording/database.idsdb", "${workspaceRoot}/fulltests/recording/const_config.bin", "${workspaceRoot}/fulltests/recording/var_config.bin"],
            "cwd": "${workspaceRoot}/xxxxxx",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ],
            "env": {"name":"value"}
        },
...
}

```   
Your settings.json:   
```json
```   // Place your settings in this file to overwrite the default settings
{
    "http.proxy": "http://127.0.0.1:3128/",
    "http.proxyStrictSSL": false,

    // Columns at which to show vertical rulers
    "editor.rulers": [79],

    // When opening a file, `editor.tabSize` and `editor.insertSpaces` will be detected based on the file contents.
    "editor.detectIndentation": false,
    // Controls whether the editor should render indent guides
    "editor.renderIndentGuides": true,

    // Controls how the editor should render whitespace characters, posibilties are 'none', 'boundary', and 'all'. The 'boundary' option does not render single spaces between words.
    "editor.renderWhitespace": "boundary",

    // Controls if the diff editor shows changes in leading or trailing whitespace as diffs
    "diffEditor.ignoreTrimWhitespace": false,

    // When enabled, will trim trailing whitespace when you save a file.
    "files.trimTrailingWhitespace": true,
    "git.confirmSync": false,
    "window.zoomLevel": -1,

    // Path to Python, you can use a custom version of Python by modifying this setting to include the full path.
    "python.pythonPath": "python3",

    // Whether to lint Python files.
    "python.linting.enabled": true,

    // Whether to lint Python files using pep8
    "python.linting.pep8Enabled": true,

    // Arguments passed in. Each argument is a separate item in the array.
    "python.linting.pep8Args": ["--ignore=E221,E226,E241"]

,
"workbench.statusBar.visible": true
}
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

Output from debug console window:
I get the same problem with version 0.5.6:
Traceback (most recent call last):
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1725, in loop
    cmd()
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 2022, in command_enum_children
    thread.enum_child_on_thread(text, cur_frame, eid, frame_kind)
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1345, in enum_child_on_thread
    self.schedule_work(lambda : self.enum_child_locally(text, cur_frame, execution_id, frame_kind))
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1316, in schedule_work
    self.unblock()
  File "/home/sni1lud/.vscode/extensions/donjayamanne.python-0.5.6/pythonFiles/PythonTools/visualstudio_py_debugger.py", line 1312, in unblock
    self._block_lock.release()
RuntimeError: release unlocked lock

Using python 3. Have some different watch variables. The problem occurs when I step inside the code.

**Comment by staffann** [comment]
When doing a search I see that this is a long lasting problem that doesn't seem to be resolved.

**Comment by DonJayamanne** [comment]
@staffann apologies for never getting back to you on this. Are you still experiencing this issue?

**Comment by renanllisboa** [comment]
Hi everyone, i'm getting this issue on vscode 1.17.2 extension 0.7.0.

**Comment by DonJayamanne** [comment]
This issue was moved to Microsoft/vscode-python#76
