### ISSUE TITLE
yapf latest version 0.16 not working with pythonVSCode

### ISSUE THREAD

**Issue by toplinuxsir** [DonJayamanne/pythonVSCode#730]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
Why do you say it doesn't work with the latest version? 
I've tested it and it seems to work just fine.
Did it work for older versions for you?

**Comment by toplinuxsir** [comment]
The strange thing is : It works  for some python source file ,but not works for other such as line number exceed 2000 lines ,
But I format the file via command directly , It always work !

**Comment by toplinuxsir** [comment]
Is there  a way to check the PythonVSCode  debug output information ?

**Comment by DonJayamanne** [comment]
Yes, there is.
1. Please check the output from the ```Python``` output channel   
2. Next, check the ```Console``` tab when you click on ```Toggle Debugger Tools``` menu option

**Comment by DonJayamanne** [comment]
Just tried it with a 6000 line file. FYI - When running yapf you'll see a message in the status bar window, and once completed this message disappears.

**Comment by toplinuxsir** [comment]
workbench.main.js:133 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 499, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 470, in _process_request
    defs = self._get_definitions(script.goto_definitions(), request['id'])
  File "preview/jedi/api/__init__.py", line 194, in goto_definitions
    module_node = self._get_module_node()
  File "preview/jedi/cache.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "preview/jedi/api/__init__.py", line 141, in _get_module_node
    parser = FastParser(self._grammar, self._source, self.path)
  File "preview/jedi/parser/diff.py", line 33, in __call__
    parser.module = parser._parsed = d.update(new_lines)
  File "preview/jedi/parser/diff.py", line 219, in update
    % (last_pos, line_length, ''.join(diff))
Exception: There's an issue (3558 != 3559) with the diff parser. Please report:
--- 
+++ 
@@ -3555,4 +3555,5 @@
 
     # delete old online_obj
     online_obj.delete()
+    # yapf: enable

**Comment by toplinuxsir** [comment]
workbench.main.js:133 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 499, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 490, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 149, in _serialize_completions
    for signature, name, value in self._get_call_signatures(script):
  File "completion.py", line 73, in _get_call_signatures
    call_signatures = script.call_signatures()
  File "preview/jedi/api/__init__.py", line 304, in call_signatures
    helpers.get_call_signature_details(self._get_module_node(), self._pos)
  File "preview/jedi/cache.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "preview/jedi/api/__init__.py", line 141, in _get_module_node
    parser = FastParser(self._grammar, self._source, self.path)
  File "preview/jedi/parser/diff.py", line 33, in __call__
    parser.module = parser._parsed = d.update(new_lines)
  File "preview/jedi/parser/diff.py", line 192, in update
    self._copy_from_old_parser(line_offset, i2, j2)
  File "preview/jedi/parser/diff.py", line 254, in _copy_from_old_parser
    line_offset
  File "preview/jedi/parser/diff.py", line 555, in copy_nodes
    new_nodes, self._tos = self._copy_nodes(tos, tree_nodes, until_line, line_offset)
  File "preview/jedi/parser/diff.py", line 625, in _copy_nodes
    tos.add(new_nodes, line_offset, last_line_offset_leaf)
  File "preview/jedi/parser/diff.py", line 440, in add
    raise NotImplementedError
NotImplementedError

**Comment by DonJayamanne** [comment]
Looks like an issue with Jedi library (upstream). will check and get back

**Comment by DonJayamanne** [comment]
@toplinuxsir are you still experiencing this issue?
