### ISSUE TITLE
NotImplementedError when using autocomplete with tensorflow

### ISSUE THREAD

**Issue by XoriieInpottn** [DonJayamanne/pythonVSCode#731]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.4
OS and version:    debian 8

## Actual behavior

The problem occurred when I am using tensorflow. After writing:
```python
import tensorflow as tf
tf.
```
there is no suggestions, and I got a NotImplementedError on the developer tools console.
My tensorflow version is 0.12.0rc1

I think the error was caused by jedi in donjayamanne.python-0.5.8/pythonFiles/preview/jedi/evaluate/instance.py:
In line 159, the value of "scope.type" is "classdef".

## Expected  behavior

In normal cases, it should show a suggestion list.

## Steps to reproduce:  
- import tensorflow as tf
- tf.
- After typing ".",  NotImplementedError was thrown.

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    "editor.fontSize": 14,
    "editor.fontFamily": "'Lucida Console'",
    "python.pythonPath": "python3",
    "editor.rulers": [
        80,
        120
    ],
    "python.linting.enabled": false,
    "editor.renderWhitespace": "all"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] ---------------------------d.logExtensionHostMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] stderr jediProxyd.logExtensionHostMessage @ //usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 499, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 490, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 185, in _serialize_completions
    'type': self._get_definition_type(completion),
  File "completion.py", line 27, in _get_definition_type
    if definition.type in ['statement'] and definition.name.isupper():
  File "preview/jedi/api/classes.py", line 146, in type
    for context in self._name.infer():
  File "preview/jedi/evaluate/filters.py", line 82, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "preview/jedi/evaluate/finder.py", line 188, in _name_to_types
    types = imports.infer_import(context, tree_name)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/evaluate/imports.py", line 69, in infer_import
    ) for t in types
  File "preview/jedi/common.py", line 186, in unite
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/common.py", line 186, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/evaluate/imports.py", line 69, in <genexpr>
    ) for t in types
  File "preview/jedi/_compatibility.py", line 185, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "preview/jedi/evaluate/context.py", line 54, in py__getattribute__
    self, name_or_str, name_context, position, search_global, is_goto)
  File "preview/jedi/evaluate/__init__.py", line 129, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/finder.py", line 63, in find
    types = self._names_to_types(names, attribute_lookup)
  File "preview/jedi/evaluate/finder.py", line 140, in _names_to_types
    types = unite(name.infer() for name in names)
  File "preview/jedi/common.py", line 186, in unite
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/common.py", line 186, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/evaluate/finder.py", line 140, in <genexpr>
    types = unite(name.infer() for name in names)
  File "preview/jedi/evaluate/filters.py", line 82, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "preview/jedi/evaluate/finder.py", line 184, in _name_to_types
    types = _remove_statements(evaluator, context, node, tree_name)
  File "preview/jedi/evaluate/finder.py", line 269, in _remove_statements
    types |= context.eval_stmt(stmt, seek_name=name)
  File "preview/jedi/evaluate/context.py", line 42, in eval_stmt
    return self.evaluator.eval_statement(self, stmt, seek_name)
  File "preview/jedi/evaluate/__init__.py", line 134, in eval_statement
    return self._eval_stmt(context, stmt, seek_name)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 150, in _eval_stmt
    types = self.eval_element(context, rhs)
  File "preview/jedi/evaluate/__init__.py", line 250, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "preview/jedi/evaluate/__init__.py", line 262, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 266, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 292, in _eval_element_not_cached
    types = self.eval_trailer(context, types, trailer)
  File "preview/jedi/evaluate/__init__.py", line 410, in eval_trailer
    new_types |= self.execute(typ, arguments)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 426, in execute
    return stdlib.execute(self, obj, arguments)
  File "preview/jedi/evaluate/stdlib.py", line 55, in execute
    return func(evaluator, obj, arguments)
  File "preview/jedi/evaluate/stdlib.py", line 250, in collections_namedtuple
    for lazy_context in _fields.py__iter__()
  File "preview/jedi/evaluate/stdlib.py", line 249, in <listcomp>
    v.obj
  File "preview/jedi/evaluate/iterable.py", line 409, in py__iter__
    for addition in check_array_additions(self._defining_context, self):
  File "preview/jedi/evaluate/iterable.py", line 702, in check_array_additions
    return _check_array_additions(context, sequence)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/iterable.py", line 772, in _check_array_additions
    cut_own_trailer=True
  File "preview/jedi/evaluate/helpers.py", line 76, in evaluate_call_of_leaf
    values = context.eval_trailer(values, trailer)
  File "preview/jedi/_compatibility.py", line 185, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "preview/jedi/evaluate/context.py", line 46, in eval_trailer
    return self.evaluator.eval_trailer(self, types, trailer)
  File "preview/jedi/evaluate/__init__.py", line 406, in eval_trailer
    name_or_str=node
  File "preview/jedi/_compatibility.py", line 185, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "preview/jedi/evaluate/context.py", line 54, in py__getattribute__
    self, name_or_str, name_context, position, search_global, is_goto)
  File "preview/jedi/evaluate/__init__.py", line 129, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/finder.py", line 63, in find
    types = self._names_to_types(names, attribute_lookup)
  File "preview/jedi/evaluate/finder.py", line 140, in _names_to_types
    types = unite(name.infer() for name in names)
  File "preview/jedi/common.py", line 186, in unite
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/common.py", line 186, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "preview/jedi/evaluate/finder.py", line 140, in <genexpr>
    types = unite(name.infer() for name in names)
  File "preview/jedi/evaluate/filters.py", line 82, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "preview/jedi/evaluate/instance.py", line 295, in parent_context
    return self._instance.create_instance_context(self.class_context, self.tree_name)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/evaluate/instance.py", line 158, in create_instance_context
    parent_context = self.create_instance_context(class_context, scope)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/evaluate/instance.py", line 169, in create_instance_context
    raise NotImplementedError
NotImplementedError
```

**Comment by toplinuxsir** [comment]
Yes, I met the same problem !

**Comment by DonJayamanne** [comment]
Looks like an issue with the Jedi library. Will check and confirm

**Comment by DonJayamanne** [comment]
Closing as this is an upstream (Jedi library used to provide intellisense) issue.
