### ISSUE TITLE
Debugger failed to start: ModuleNotFoundError

### ISSUE THREAD

**Issue by chengyuhui** [DonJayamanne/pythonVSCode#734]
## Environment data
VS Code version:  1.9.1
Python Extension version:  0.5.8
Python Version:   3.6.0
OS and version:    Windows 10 14393

## Actual behavior
```
cd 'f:\wrap'; $env:PYTHONIOENCODING='UTF-8'; f:\wrap/bin/python/python.exe C:\Users\cheng\.vsco
de\extensions\donjayamanne.python-0.5.8\pythonFiles\PythonTools\visualstudio_py_launcher.py f:\wrap 12282 34806ad9-833a-4524-8cd
6-18ca4aa74f14 WaitOnAbnormalExit,WaitOnNormalExit f:\wrap/runner.py --workdir Z:\ --debug video --preview --resource fixtures/r
esource/resource.yml fixtures/profile.yml
Traceback (most recent call last):
  File "C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\pythonFiles\PythonTools\visualstudio_py_launcher.py", line 3
1, in <module>
    import visualstudio_py_debugger as vspd
ModuleNotFoundError: No module named 'visualstudio_py_debugger'

Internal error detected. Please copy the above traceback and report at
http://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .
```

## Expected  behavior
Starts debugging

## Steps to reproduce:  
-  Install Python 3.6 and set it as workspace python ( I am using WinPython-64bit-3.6.0.1Zero)
-  Start debugging

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Preview",
            "type": "python",
            "program": "${workspaceRoot}/runner.py",
            "request": "launch",
            "pythonPath": "${config.python.pythonPath}",
            "stopOnEntry": false,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "RedirectOutput",
                "WaitOnNormalExit"
            ],
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "args": [
                "--workdir", "Z:\\",
                "--debug",
                "video",
                "--preview",
                "--resource", "fixtures/resource/resource.yml",
                "fixtures/profile.yml"
            ]
        },
        {
            "name": "Launch Output",
            "type": "python",
            "program": "${workspaceRoot}/runner.py",
            "request": "launch",
            "pythonPath": "${config.python.pythonPath}",
            "stopOnEntry": false,
            "debugOptions": [
                "WaitOnAbnormalExit",
                "RedirectOutput",
                "WaitOnNormalExit"
            ],
            "cwd": "${workspaceRoot}",
            "console": "integratedTerminal",
            "args": [
                "--workdir", "Z:\\",
                "--debug",
                "video",
                "--output", "Z:\\out.mp4",
                "--resource", "fixtures/resource/resource.yml",
                "fixtures/profile.yml"
            ]
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.linting.pylintEnabled": true,
    "python.linting.pylintPath": "${workspaceRoot}/bin/python_wrapper/pylint.bat",
    "python.linting.pylintCategorySeverity.convention": "Information",
    "python.linting.pylintCategorySeverity.refactor": "Hint",
    "python.formatting.autopep8Path": "${workspaceRoot}/bin/python_wrapper/autopep8.bat",
    "python.pythonPath": "${workspaceRoot}/bin/python/python.exe",
    "python.autoComplete.extraPaths": [
        "${workspaceRoot}/lib"
    ],
    "python.workspaceSymbols.exclusionPatterns": [
        "bin"
    ]
}
```   
## Logs
Output from ```Python``` output panel  
```
##########Linting Output - pylint##########
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
[uncaught exception]: Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\out\client\debugger\Main.js:328:27)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\out\client\debugger\Main.js:328:27)
    at PythonDebugger.DebugSession.dispatchRequest (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\cheng\.vscode\extensions\donjayamanne.python-0.5.8\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:93:15762
    at Object.v [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:12913)
    at Object.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:16418)
    at _run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17739)
    at _error (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:17256)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:86:24095
    at g.e.dispatch (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:86:25446)
    at g.e.handleData (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:86:24954)
    at Socket.<anonymous> (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:86:23955)
    at emitOne (events.js:96:13)
WARNING: Promise with no error callback:86
```

**Comment by chengyuhui** [comment]
Problem found: _pth file in python dir.
