### ISSUE TITLE
Refactor (renaming) symbols not working

### ISSUE THREAD

**Issue by funvit** [DonJayamanne/pythonVSCode#875]
## Environment data
VS Code version:  1.11.1
Python Extension version:  
Python Version:   3.6
OS and version:    OSX 10.12.4 

## Actual behavior
Renaming symbol (class name or method) not renaming it in other files

## Expected  behavior
Renaming in all files

## Steps to reproduce:  
-  open file with base class
-  select class name
-  press F2
-  change name
-  hit enter

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   

basic

## Logs
Output from ```Python``` output panel  

clear

Output from ```Console window``` (Help->Developer Tools menu)
```
shell.ts:475 channel closed: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at IPCMessageWriter.write (/Users/user/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/messageWriter.js:34:22)
    at Object.sendNotification (/Users/user/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-jsonrpc/lib/main.js:180:27)
    at Object.didChangeTextDocument (/Users/user/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:55:70)
    at Delayer.task (/Users/user/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/main.js:373:28)
    at /Users/user/.vscode/extensions/tht13.python-0.2.3/node_modules/vscode-languageclient/lib/utils/async.js:27:36
```

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/DonJayamanne/pythonVSCode/issues/824
