### ISSUE TITLE
Intellisense not working with extra paths specified, jedi errors in developer console

### ISSUE THREAD

**Issue by riverar** [DonJayamanne/pythonVSCode#886]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.2
Python Version:  2.7.11 (x86)
OS and version:  Windows 10 16170.1000

## Actual behavior
Added unregistered libraries to auto-complete extra paths. Intellisense doesn't work at all.

## Expected  behavior
Intellisense should work for libraries added to path.

## Steps to reproduce:  
1. Have libs on disk somewhere that aren't pip-installed/registered
2. Edit extraPaths per wiki guidance
3. Try using Intellisense

## Settings  
settings.json
```
{
    "python.pythonPath": "C:/Python27/python.exe",
    "python.autoComplete.extraPaths": [
        "C:/Program Files (x86)/IDA 6.8/python",
     ]
}
```
## Logs
developer console
```
[Extension Host] ---------------------------
[Extension Host] stderr jediProxy
[Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 582, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview\jedi\api\__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview\jedi\api\completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview\jedi\api\completion.py", line 164, in _get_context_completions
    completion_names += self._trailer_completions(atom_expr)
  File "preview\jedi\api\completion.py", line 201, in _trailer_completions
    scopes = self._evaluator.eval_element(atom_expr)
  File "preview\jedi\evaluate\__init__.py", line 263, in eval_element
    return self._eval_element_if_evaluated(element)
  File "preview\jedi\evaluate\__init__.py", line 276, in _eval_element_if_evaluated
    return self._eval_element_cached(element)
  File "preview\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\evaluate\__init__.py", line 280, in _eval_element_cached
    return self._eval_element_not_cached(element)
  File "preview\jedi\debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview\jedi\evaluate\__init__.py", line 287, in _eval_element_not_cached
    types = self._eval_atom(element)
  File "preview\jedi\evaluate\__init__.py", line 358, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "preview\jedi\evaluate\__init__.py", line 143, in find_types
    return f.find(scopes, attribute_lookup=not search_global)
  File "preview\jedi\debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview\jedi\evaluate\finder.py", line 104, in find
    types = self._names_to_types(names, attribute_lookup)
  File "preview\jedi\evaluate\finder.py", line 293, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "preview\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\evaluate\finder.py", line 354, in _name_to_types
    types = imports.ImportWrapper(evaluator, name).follow()
  File "preview\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\evaluate\imports.py", line 89, in follow
    types = importer.follow()
  File "preview\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview\jedi\evaluate\imports.py", line 246, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "preview\jedi\evaluate\imports.py", line 342, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path, parent_module)
  File "preview\jedi\evaluate\imports.py", line 458, in _load_module
    module = load(source) if cached is None else cached.module
  File "preview\jedi\evaluate\imports.py", line 449, in load
    p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source), p)
  File "preview\jedi\common.py", line 148, in source_to_unicode
    return unicode(source, encoding, 'replace')
MemoryError
```

**Comment by DonJayamanne** [comment]
Unfortunately, the 3rd party library is falling over with a memory error.  
Have you tried this with a smaller set of files, possible the Jedi library is trying to scan too many files/folders and running low on resources.

**Comment by riverar** [comment]
The path above only has 5 .py files and there's certainly not a low resource issue. Recommend re-opening this bug until the actual problem is determined.
