### ISSUE TITLE
Debugging unit test: NameError: global name 'rich_exceptions' is not defined

### ISSUE THREAD

**Issue by akobler** [DonJayamanne/pythonVSCode#893]
Hi

I encountered the following issue when I wanted to debug unit tests with this cool VS code python extension (thanks a lot for providing it). I am going to look at the issue as well, but as I am new to VS code extension dev, you might be faster in spotting the bug. What I have seen so far, the parameter is named `connrich_exceptions`, but in the function body the variable `rich_exceptions` is used.

Best, Andi

## Environment data
VS Code version: 1.11.2, 6eaebe3b9c70406d67c97779468c324a7a95db0e
Python Extension version: 0.6.2
Python Version: 2.7.10
OS and version: OSX 10.11.6 (15G31)

## Actual behavior
If I start debugging a python unit test, the following exception gets shown in tht VS code output console and the unit test is not run.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/attach_server.py", line 257, in server_thread_func
    vspd.attach_process_from_socket(client, debug_options, report = True)
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/visualstudio_py_debugger.py", line 2360, in attach_process_from_socket
    debugger_thread_id = _start_new_thread(DebuggerLoop(conn).loop, ())
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/visualstudio_py_debugger.py", line 1693, in __init__
    self.rich_exceptions = rich_exceptions
NameError: global name 'rich_exceptions' is not defined
```

## Expected  behavior
Run the unit test function in debug mode.

## Steps to reproduce:  
- "shift+cmd+p"
- ">Python: Debug Unit Test Method..."
- enter the name of the unit test function

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}/scripts/common/",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }
    ]
}
```   
Your settings.json:   
```json
{
    "python.unitTest.pyTestEnabled": false,
    "python.unitTest.unittestEnabled": true,
    "python.unitTest.nosetestsEnabled": false,
    "python.unitTest.unittestArgs": [
        "-v",
        "-s",
        "./scripts/common",
        "-p",
        "*Test.py"
    ],
    "search.exclude": {
        "**/.git": true,
        "**/node_modules": true,
        "**/debian": true,
        "**/temp": true
    }
}
```   
## Logs
Output from ```Python``` output panel  

list of all test functions, then:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/attach_server.py", line 257, in server_thread_func
    vspd.attach_process_from_socket(client, debug_options, report = True)
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/visualstudio_py_debugger.py", line 2360, in attach_process_from_socket
    debugger_thread_id = _start_new_thread(DebuggerLoop(conn).loop, ())
  File "/Users/andreas/.vscode/extensions/donjayamanne.python-0.6.2/pythonFiles/PythonTools/ptvsd/visualstudio_py_debugger.py", line 1693, in __init__
    self.rich_exceptions = rich_exceptions
NameError: global name 'rich_exceptions' is not defined
```   

Output from ```Console window``` (Help->Developer Tools menu)
```
messageService.ts:126 There was an error in running the tests.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by xqliu** [comment]
I also have this issue when trying to run a unittest test class.

Also system runs *all the unit tests* when I click the "Run test" lens before one method.

I suppose only one method should be run, right?

That's quite wired.

**Comment by nilleb** [comment]
I suppose that the author has shipped the 0.6.2 version with a few typos in it :) 
https://github.com/DonJayamanne/pythonVSCode/commit/335c16d2940879141a94f60e6d551f034a867a23


IMHO to fix this issue, @DonJayamanne should just build and ship a 0.6.3...

**Comment by DonJayamanne** [comment]
Fixed, will release a new version today.
https://github.com/DonJayamanne/pythonVSCode/commit/b878a028f69b0aacdaac7609a686752ca4e99ffe

**Comment by akobler** [comment]
Thanks a lot, works great again!
