### ISSUE TITLE
Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by Cologler** [DonJayamanne/pythonVSCode#904]
## Environment data
VS Code version:  1.11.2
Python Extension version:  0.6.3
Python Version:   3.6
OS and version:   win 10 x64

## Logs

Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] Here is the error stack:  Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\巍\.vscode\extensions\donjayamanne.python-0.6.3\out\client\unittests\common\xUnitParser.js:4:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by Cologler** [comment]
after execute command `npm install` on the extension directory, problem is resolved.

**Comment by Cologler** [comment]
this maybe the vscode's bug.

**Comment by DonJayamanne** [comment]
No it isn't. My bug,😥

**Comment by Cologler** [comment]
o(*≧▽≦)ツ┏━┓

**Comment by DonJayamanne** [comment]
Fixed in latest version, will release a new update
