### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by artyomboyko** [DonJayamanne/pythonVSCode#915]
## Environment data
VS Code version:  
1.12.0-insider (1.12.0-insider)
Python Extension version:  
0.6.3
Python Version:   
2.7.13
OS and version:    
macOS Sierra 10.12.4
## Actual behavior

Debug adapter process has terminated unexpectedly

## Expected  behavior

Successful debugging. I'm testing no the same machine, no virtual environment (no VM, no docker)

## Steps to reproduce:  

```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()

s = 0

while True:
    s += 1
    print('asda')
    import time
    time.sleep(3)
```

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
```json
// empty
```   
## Logs
Output from ```Python``` output panel  
```
nothing
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
[uncaught exception]: Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/out/client/debugger/Main.js:340:27)
    at PythonDebugger.DebugSession.dispatchRequest (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
onError @ index.js:5
index.js:5 Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/out/client/debugger/Main.js:340:27)
    at PythonDebugger.DebugSession.dispatchRequest (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/Users/artyomboyko/.vscode-insiders/extensions/donjayamanne.python-0.6.3/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2354688
    at Object.v [as _notify] (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:69851)
    at Object.enter (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:73352)
    at n.Class.derive._oncancel._run (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:74673)
    at n.Class.derive._oncancel._error (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:74190)
    at file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2052007
    at g.e.dispatch (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2053358)
    at g.e.handleData (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2052866)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2051867)
    at emitOne (events.js:96:13)
```

**Comment by DonJayamanne** [comment]
The following code is used for remote debugging.
```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()
```

Please provide more information on what you are trying to do and how exactly to replicate the issue (provide the steps).

**Comment by artyomboyko** [comment]
I'm trying to make minimal example to test remote debugging, because it doesn't work for me on docker. Looks like it doesn't even work locally.

So I have this server.py script

```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()

s = 0

while True:
    s += 1
    print('asda')
    import time
    time.sleep(3)
```

I'm trying to debug this script (the while loop).
I'm running `python server.py` then open my IDE. And I trying to connect using remote debugger (attach method. you can see configuration at the top). 
Python script hangs indefinitely and IDE gives me error.

**Comment by artyomboyko** [comment]
@DonJayamanne maybe screenshots will help http://imgur.com/a/vIzGN
Of course I'm executing debugging inside the editor. I've spend a lot of hours on this. 
It started as problem with debugging inside docker, but it turns out I can even run it locally. Of course there is a high change I'm doing something wrong (because it works for a lot of people), but I can't see what exactly. I've read every article about python debugging in vscode there is.

**Comment by artyomboyko** [comment]
Or, for example

asd.py
```python
s = 0

while True:
    s += 1
    print('asda')
    import time
    time.sleep(3)
```
Running as `python -m ptvsd --port=3000 asd.py`

Then I open `asd.py` in the editor. Click on Remote Debugging - and I'm getting the same error

**Comment by DonJayamanne** [comment]
Works at my end, here are the instructions:
1. Create a folder named ```Testing```  
2. Open the ```Testing``` folder from VS Code  
3. Create a file named ```one.py```  with the following contents:  
```python
import ptvsd
ptvsd.enable_attach("my_secret", address = ('0.0.0.0', 3000))
ptvsd.wait_for_attach()

s = 0

while True:
    s += 1
    print('asda')
    import time
    time.sleep(3)
```
4. Open the terminal window and type the following command:  
```pip install ptvsd```  
5. Run the following command in the terminal window:  
```python one.py```  
6. Attach the debugger  
7. Add a break point to the ```print('asda')``` line and it will break.
