### ISSUE TITLE
"Go to definition" doesn't work in "await" statements

### ISSUE THREAD

**Issue by dangusev** [DonJayamanne/pythonVSCode#962]
## Environment data
VS Code version:  1.12.2, Shell 1.6.6, Renderer 56.0.2924.87, Node 7.4.0
Python Extension version: 0.6.4
Python Version:   3.5.2
OS and version:    Ubuntu 16.04 (kernel 4.8.0-52)

## Actual behavior
Go to definition doesn't work when I press Ctrl+Click on e.g. "channel" in following statement:
```python
await self.channel.queue_declare()
```
Everything works fine if I remove "await" before statement
Errors from devtools are listed below.

## Expected  behavior
"Go to definition" shows the definition of statement

## Steps to reproduce:  
-  Set some python3.5+ in python.pythonPath
-  Type following text in editor:
```python
class A:
    def __init__(self):
        self.test_value = 0

    async def test(self):
        pass

    async def test2(self):
        await self.test()
```
- Press Ctrl+Click on "test" in await self.test()

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
{
    // Place your settings in this file to overwrite the default 
    "workbench.colorTheme": "One Dark Pro",
    "editor.fontFamily": "'Ubuntu Mono', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",
    "editor.fontSize": 19,
    "editor.rulers": [
        120
    ],
    "editor.renderIndentGuides": true,
    // Controls the line height. Use 0 to compute the lineHeight from the fontSize.
    "editor.lineHeight": 0,
    "workbench.iconTheme": "material-icon-theme",
    "editor.tabCompletion": true,
    // Python settings
    "python.venvPath": "*****",
    "python.formatting.provider": "autopep8",
    "python.formatting.yapfArgs": [],
    "python.linting.pylintArgs": [
        "--rcfile=.pylintrc"
    ],
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    // Sidebar settings
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/__pycache__": true,
        "**/.idea": true,
        "**/.vscode": true,
        "**/.cache": true,
        "**/.atom": true,
        "**/*.pyc": true
    },
    "window.zoomLevel": 0.25,
    "files.autoSave": "afterDelay",
    "vsicons.dontShowNewVersionMessage": true,
    "python.formatting.autopep8Args": [],
    
    "editor.codeLens": false,
    "extensions.autoUpdate": true,
    "projectManager.projectsLocation": "*****"
}
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
[Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 582, in watch
    self._process_request(self._input.readline())
  File "completion.py", line 548, in _process_request
    defs = self._get_definitionsx(script.goto_definitions(), request['id'])
  File "preview/jedi/api/__init__.py", line 194, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, leaf)
  File "preview/jedi/api/helpers.py", line 211, in evaluate_goto_definition
    return evaluator.goto_definitions(leaf)
  File "preview/jedi/evaluate/__init__.py", line 463, in goto_definitions
    return self.eval_element(call)
  File "preview/jedi/evaluate/__init__.py", line 263, in eval_element
    return self._eval_element_if_evaluated(element)
  File "preview/jedi/evaluate/__init__.py", line 276, in _eval_element_if_evaluated
    return self._eval_element_cached(element)
  File "preview/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 280, in _eval_element_cached
    return self._eval_element_not_cached(element)
  File "preview/jedi/debug.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "preview/jedi/evaluate/__init__.py", line 300, in _eval_element_not_cached
    types = self._eval_atom(element.children[0])
  File "preview/jedi/evaluate/__init__.py", line 362, in _eval_atom
    c = atom.children
AttributeError: 'Keyword' object has no attribute 'children'
```

**Comment by DonJayamanne** [comment]
Unable to replicate this issue, please reopen if the problem persists. I believe it may have been fixed in a subsequent release of the extension.
