### ISSUE TITLE
"Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by m0ngr31** [DonJayamanne/pythonVSCode#985]
## Environment data
VS Code version: 1.12.2
Python Extension version: 0.6.4
Python Version: 2.7.13
OS and version: Ubuntu 17.04

## Actual behavior
Trying to debug server, and I get the message: "Debug adapter process has terminated unexpectedly", even though the server is running fine in the terminal.

## Expected  behavior
Have debugging working? It working fine in PyCharm (But I run with the "Gevent compatible" setting).

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
{
    "name": "Work",
    "type": "python",
    "request": "launch",
    "stopOnEntry": false,
    "program": "${workspaceRoot}/beam/web/run_services.py",
    "cwd": "${workspaceRoot}/beam/web",
    "console": "integratedTerminal",
    "env": {
        ...
    },
    "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit"
    ]
}
```   
Your settings.json:   
```json
// Place your settings in this file to overwrite default and user settings.
{
    "python.pythonPath": "/home/myuser/.virtualenvs/work_env/bin/python",
    "python.autoComplete.extraPaths": [
        "/home/myuser/.virtualenvs/work_env/bin/",
        "/home/myuser/.virtualenvs/work_env/lib/python2.7/site-packages"
    ]
}
```

Output from ```Console window``` (Help->Developer Tools menu)
```
TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/out/client/debugger/Main.js:340:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20): Error: TypeError: Cannot read property 'Threads' of undefined
    at PythonDebugger.threadsRequest (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/out/client/debugger/Main.js:340:27)
    at PythonDebugger.DebugSession.dispatchRequest (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/debugSession.js:427:22)
    at PythonDebugger.ProtocolServer._handleData (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/protocol.js:104:38)
    at Socket.<anonymous> (/home/myuser/.vscode/extensions/donjayamanne.python-0.6.4/node_modules/vscode-debugadapter/lib/protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:2217016
    at Object.v [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:68877)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:72378)
    at n.Class.derive._oncancel._run (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:73699)
    at n.Class.derive._oncancel._error (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:73216)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1952866
    at g.e.dispatch (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1954217)
    at g.e.handleData (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1953725)
    at Socket.<anonymous> (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28:1952726)
    at emitOne (events.js:96:13)
```

**Comment by m0ngr31** [comment]
The frustrating thing about this is that it will work intermittently. Maybe like 1/6 times?

**Comment by Dlizzz** [comment]
Never work on my side: [https://github.com/DonJayamanne/pythonVSCode/issues/981]

How do you get this output on the Console window?

**Comment by DonJayamanne** [comment]
@m0ngr31 Are you trying to debug something remotely or locally. 
If its a remote debugging issue, then please ensure you are using PTVSD version 3.0.0 and not a later version.

**Comment by m0ngr31** [comment]
@DonJayamanne I'm trying to debug locally.

**Comment by DonJayamanne** [comment]
@m0ngr31 I take it its still not working?

**Comment by m0ngr31** [comment]
Yeah, unfortunately I still have to use PyCharm

**Comment by DonJayamanne** [comment]
@m0ngr31 I'll have a look into this some time today.
Please could you provide some sample code used to replicate this issue.

**Comment by m0ngr31** [comment]
Unfortunately all the code is proprietary, so it'll be hard to break out into something to give you to replicate. But I think #1000 is the same issue.

**Comment by DonJayamanne** [comment]
@m0ngr31 so, this happens only in a certain scenario. I.e. debugging works for simple code.

**Comment by m0ngr31** [comment]
Yes, as far as I've seen

**Comment by m0ngr31** [comment]
So if you want to close this as a duplicate, that's fine.
